// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package aws

import (
	"context"
	"reflect"

	"github.com/DefangLabs/pulumi-defang/sdk/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type SharedInfra struct {
	PrivateSubnetIDs []string `pulumi:"privateSubnetIDs"`
	PrivateZoneID    *string  `pulumi:"privateZoneID"`
	PublicSubnetIDs  []string `pulumi:"publicSubnetIDs"`
	VpcID            string   `pulumi:"vpcID"`
}

// SharedInfraInput is an input type that accepts SharedInfraArgs and SharedInfraOutput values.
// You can construct a concrete instance of `SharedInfraInput` via:
//
//	SharedInfraArgs{...}
type SharedInfraInput interface {
	pulumi.Input

	ToSharedInfraOutput() SharedInfraOutput
	ToSharedInfraOutputWithContext(context.Context) SharedInfraOutput
}

type SharedInfraArgs struct {
	PrivateSubnetIDs pulumi.StringArrayInput `pulumi:"privateSubnetIDs"`
	PrivateZoneID    pulumi.StringPtrInput   `pulumi:"privateZoneID"`
	PublicSubnetIDs  pulumi.StringArrayInput `pulumi:"publicSubnetIDs"`
	VpcID            pulumi.StringInput      `pulumi:"vpcID"`
}

func (SharedInfraArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SharedInfra)(nil)).Elem()
}

func (i SharedInfraArgs) ToSharedInfraOutput() SharedInfraOutput {
	return i.ToSharedInfraOutputWithContext(context.Background())
}

func (i SharedInfraArgs) ToSharedInfraOutputWithContext(ctx context.Context) SharedInfraOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SharedInfraOutput)
}

func (i SharedInfraArgs) ToSharedInfraPtrOutput() SharedInfraPtrOutput {
	return i.ToSharedInfraPtrOutputWithContext(context.Background())
}

func (i SharedInfraArgs) ToSharedInfraPtrOutputWithContext(ctx context.Context) SharedInfraPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SharedInfraOutput).ToSharedInfraPtrOutputWithContext(ctx)
}

// SharedInfraPtrInput is an input type that accepts SharedInfraArgs, SharedInfraPtr and SharedInfraPtrOutput values.
// You can construct a concrete instance of `SharedInfraPtrInput` via:
//
//	        SharedInfraArgs{...}
//
//	or:
//
//	        nil
type SharedInfraPtrInput interface {
	pulumi.Input

	ToSharedInfraPtrOutput() SharedInfraPtrOutput
	ToSharedInfraPtrOutputWithContext(context.Context) SharedInfraPtrOutput
}

type sharedInfraPtrType SharedInfraArgs

func SharedInfraPtr(v *SharedInfraArgs) SharedInfraPtrInput {
	return (*sharedInfraPtrType)(v)
}

func (*sharedInfraPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SharedInfra)(nil)).Elem()
}

func (i *sharedInfraPtrType) ToSharedInfraPtrOutput() SharedInfraPtrOutput {
	return i.ToSharedInfraPtrOutputWithContext(context.Background())
}

func (i *sharedInfraPtrType) ToSharedInfraPtrOutputWithContext(ctx context.Context) SharedInfraPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SharedInfraPtrOutput)
}

type SharedInfraOutput struct{ *pulumi.OutputState }

func (SharedInfraOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SharedInfra)(nil)).Elem()
}

func (o SharedInfraOutput) ToSharedInfraOutput() SharedInfraOutput {
	return o
}

func (o SharedInfraOutput) ToSharedInfraOutputWithContext(ctx context.Context) SharedInfraOutput {
	return o
}

func (o SharedInfraOutput) ToSharedInfraPtrOutput() SharedInfraPtrOutput {
	return o.ToSharedInfraPtrOutputWithContext(context.Background())
}

func (o SharedInfraOutput) ToSharedInfraPtrOutputWithContext(ctx context.Context) SharedInfraPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SharedInfra) *SharedInfra {
		return &v
	}).(SharedInfraPtrOutput)
}

func (o SharedInfraOutput) PrivateSubnetIDs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SharedInfra) []string { return v.PrivateSubnetIDs }).(pulumi.StringArrayOutput)
}

func (o SharedInfraOutput) PrivateZoneID() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SharedInfra) *string { return v.PrivateZoneID }).(pulumi.StringPtrOutput)
}

func (o SharedInfraOutput) PublicSubnetIDs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SharedInfra) []string { return v.PublicSubnetIDs }).(pulumi.StringArrayOutput)
}

func (o SharedInfraOutput) VpcID() pulumi.StringOutput {
	return o.ApplyT(func(v SharedInfra) string { return v.VpcID }).(pulumi.StringOutput)
}

type SharedInfraPtrOutput struct{ *pulumi.OutputState }

func (SharedInfraPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SharedInfra)(nil)).Elem()
}

func (o SharedInfraPtrOutput) ToSharedInfraPtrOutput() SharedInfraPtrOutput {
	return o
}

func (o SharedInfraPtrOutput) ToSharedInfraPtrOutputWithContext(ctx context.Context) SharedInfraPtrOutput {
	return o
}

func (o SharedInfraPtrOutput) Elem() SharedInfraOutput {
	return o.ApplyT(func(v *SharedInfra) SharedInfra {
		if v != nil {
			return *v
		}
		var ret SharedInfra
		return ret
	}).(SharedInfraOutput)
}

func (o SharedInfraPtrOutput) PrivateSubnetIDs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SharedInfra) []string {
		if v == nil {
			return nil
		}
		return v.PrivateSubnetIDs
	}).(pulumi.StringArrayOutput)
}

func (o SharedInfraPtrOutput) PrivateZoneID() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SharedInfra) *string {
		if v == nil {
			return nil
		}
		return v.PrivateZoneID
	}).(pulumi.StringPtrOutput)
}

func (o SharedInfraPtrOutput) PublicSubnetIDs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SharedInfra) []string {
		if v == nil {
			return nil
		}
		return v.PublicSubnetIDs
	}).(pulumi.StringArrayOutput)
}

func (o SharedInfraPtrOutput) VpcID() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SharedInfra) *string {
		if v == nil {
			return nil
		}
		return &v.VpcID
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SharedInfraInput)(nil)).Elem(), SharedInfraArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SharedInfraPtrInput)(nil)).Elem(), SharedInfraArgs{})
	pulumi.RegisterOutputType(SharedInfraOutput{})
	pulumi.RegisterOutputType(SharedInfraPtrOutput{})
}
