// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangaws

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Build struct {
	pulumi.CustomResourceState

	BuildId     pulumi.StringOutput      `pulumi:"buildId"`
	Destination pulumi.StringPtrOutput   `pulumi:"destination"`
	Image       pulumi.StringOutput      `pulumi:"image"`
	MaxWaitTime pulumi.IntPtrOutput      `pulumi:"maxWaitTime"`
	ProjectName pulumi.StringOutput      `pulumi:"projectName"`
	Region      pulumi.StringPtrOutput   `pulumi:"region"`
	Triggers    pulumi.StringArrayOutput `pulumi:"triggers"`
}

// NewBuild registers a new resource with the given unique name, arguments, and options.
func NewBuild(ctx *pulumi.Context,
	name string, args *BuildArgs, opts ...pulumi.ResourceOption) (*Build, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectName == nil {
		return nil, errors.New("invalid value for required argument 'ProjectName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Build
	err := ctx.RegisterResource("defang-aws:index:Build", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBuild gets an existing Build resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBuild(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BuildState, opts ...pulumi.ResourceOption) (*Build, error) {
	var resource Build
	err := ctx.ReadResource("defang-aws:index:Build", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Build resources.
type buildState struct {
}

type BuildState struct {
}

func (BuildState) ElementType() reflect.Type {
	return reflect.TypeOf((*buildState)(nil)).Elem()
}

type buildArgs struct {
	Destination *string  `pulumi:"destination"`
	MaxWaitTime *int     `pulumi:"maxWaitTime"`
	ProjectName string   `pulumi:"projectName"`
	Region      *string  `pulumi:"region"`
	Triggers    []string `pulumi:"triggers"`
}

// The set of arguments for constructing a Build resource.
type BuildArgs struct {
	Destination pulumi.StringPtrInput
	MaxWaitTime pulumi.IntPtrInput
	ProjectName pulumi.StringInput
	Region      pulumi.StringPtrInput
	Triggers    pulumi.StringArrayInput
}

func (BuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*buildArgs)(nil)).Elem()
}

type BuildInput interface {
	pulumi.Input

	ToBuildOutput() BuildOutput
	ToBuildOutputWithContext(ctx context.Context) BuildOutput
}

func (*Build) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (i *Build) ToBuildOutput() BuildOutput {
	return i.ToBuildOutputWithContext(context.Background())
}

func (i *Build) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildOutput)
}

type BuildOutput struct{ *pulumi.OutputState }

func (BuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (o BuildOutput) ToBuildOutput() BuildOutput {
	return o
}

func (o BuildOutput) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return o
}

func (o BuildOutput) BuildId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.BuildId }).(pulumi.StringOutput)
}

func (o BuildOutput) Destination() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.Destination }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

func (o BuildOutput) MaxWaitTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.IntPtrOutput { return v.MaxWaitTime }).(pulumi.IntPtrOutput)
}

func (o BuildOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

func (o BuildOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Triggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Build) pulumi.StringArrayOutput { return v.Triggers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BuildInput)(nil)).Elem(), &Build{})
	pulumi.RegisterOutputType(BuildOutput{})
}
