// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangaws

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/aws"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/compose"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ObjectStore struct {
	pulumi.ResourceState

	Arn      pulumi.StringOutput `pulumi:"arn"`
	Bucket   pulumi.StringOutput `pulumi:"bucket"`
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	Region   pulumi.StringOutput `pulumi:"region"`
}

// NewObjectStore registers a new resource with the given unique name, arguments, and options.
func NewObjectStore(ctx *pulumi.Context,
	name string, args *ObjectStoreArgs, opts ...pulumi.ResourceOption) (*ObjectStore, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ObjectStore == nil {
		return nil, errors.New("invalid value for required argument 'ObjectStore'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ObjectStore
	err := ctx.RegisterRemoteComponentResource("defang-aws:index:ObjectStore", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type objectStoreArgs struct {
	Aws         *aws.SharedInfra          `pulumi:"aws"`
	Deploy      *compose.DeployConfig     `pulumi:"deploy"`
	Environment map[string]string         `pulumi:"environment"`
	Image       *string                   `pulumi:"image"`
	ObjectStore compose.ObjectStoreConfig `pulumi:"objectStore"`
	ProjectName string                    `pulumi:"projectName"`
}

// The set of arguments for constructing a ObjectStore resource.
type ObjectStoreArgs struct {
	Aws         aws.SharedInfraPtrInput
	Deploy      compose.DeployConfigPtrInput
	Environment pulumi.StringMapInput
	Image       *string
	ObjectStore compose.ObjectStoreConfigInput
	ProjectName string
}

func (ObjectStoreArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStoreArgs)(nil)).Elem()
}

type ObjectStoreInput interface {
	pulumi.Input

	ToObjectStoreOutput() ObjectStoreOutput
	ToObjectStoreOutputWithContext(ctx context.Context) ObjectStoreOutput
}

func (*ObjectStore) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStore)(nil)).Elem()
}

func (i *ObjectStore) ToObjectStoreOutput() ObjectStoreOutput {
	return i.ToObjectStoreOutputWithContext(context.Background())
}

func (i *ObjectStore) ToObjectStoreOutputWithContext(ctx context.Context) ObjectStoreOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStoreOutput)
}

type ObjectStoreOutput struct{ *pulumi.OutputState }

func (ObjectStoreOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStore)(nil)).Elem()
}

func (o ObjectStoreOutput) ToObjectStoreOutput() ObjectStoreOutput {
	return o
}

func (o ObjectStoreOutput) ToObjectStoreOutputWithContext(ctx context.Context) ObjectStoreOutput {
	return o
}

func (o ObjectStoreOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStore) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

func (o ObjectStoreOutput) Bucket() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStore) pulumi.StringOutput { return v.Bucket }).(pulumi.StringOutput)
}

func (o ObjectStoreOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStore) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

func (o ObjectStoreOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStore) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStoreInput)(nil)).Elem(), &ObjectStore{})
	pulumi.RegisterOutputType(ObjectStoreOutput{})
}
