// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangaws

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/aws"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/compose"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Postgres struct {
	pulumi.ResourceState

	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
}

// NewPostgres registers a new resource with the given unique name, arguments, and options.
func NewPostgres(ctx *pulumi.Context,
	name string, args *PostgresArgs, opts ...pulumi.ResourceOption) (*Postgres, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Postgres
	err := ctx.RegisterRemoteComponentResource("defang-aws:index:Postgres", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type postgresArgs struct {
	Aws          *aws.SharedInfra        `pulumi:"aws"`
	Deploy       *compose.DeployConfig   `pulumi:"deploy"`
	Environment  map[string]string       `pulumi:"environment"`
	Image        *string                 `pulumi:"image"`
	Postgres     *compose.PostgresConfig `pulumi:"postgres"`
	Project_name string                  `pulumi:"project_name"`
}

// The set of arguments for constructing a Postgres resource.
type PostgresArgs struct {
	Aws          aws.SharedInfraPtrInput
	Deploy       compose.DeployConfigPtrInput
	Environment  pulumi.StringMapInput
	Image        *string
	Postgres     compose.PostgresConfigPtrInput
	Project_name string
}

func (PostgresArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresArgs)(nil)).Elem()
}

type PostgresInput interface {
	pulumi.Input

	ToPostgresOutput() PostgresOutput
	ToPostgresOutputWithContext(ctx context.Context) PostgresOutput
}

func (*Postgres) ElementType() reflect.Type {
	return reflect.TypeOf((**Postgres)(nil)).Elem()
}

func (i *Postgres) ToPostgresOutput() PostgresOutput {
	return i.ToPostgresOutputWithContext(context.Background())
}

func (i *Postgres) ToPostgresOutputWithContext(ctx context.Context) PostgresOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresOutput)
}

type PostgresOutput struct{ *pulumi.OutputState }

func (PostgresOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Postgres)(nil)).Elem()
}

func (o PostgresOutput) ToPostgresOutput() PostgresOutput {
	return o
}

func (o PostgresOutput) ToPostgresOutputWithContext(ctx context.Context) PostgresOutput {
	return o
}

func (o PostgresOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Postgres) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresInput)(nil)).Elem(), &Postgres{})
	pulumi.RegisterOutputType(PostgresOutput{})
}
