// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangaws

import (
	"context"
	"reflect"

	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AWSConfig struct {
	ProjectDomain *string `pulumi:"projectDomain"`
	PublicZoneId  *string `pulumi:"publicZoneId"`
}

// AWSConfigInput is an input type that accepts AWSConfigArgs and AWSConfigOutput values.
// You can construct a concrete instance of `AWSConfigInput` via:
//
//	AWSConfigArgs{...}
type AWSConfigInput interface {
	pulumi.Input

	ToAWSConfigOutput() AWSConfigOutput
	ToAWSConfigOutputWithContext(context.Context) AWSConfigOutput
}

type AWSConfigArgs struct {
	ProjectDomain pulumi.StringPtrInput `pulumi:"projectDomain"`
	PublicZoneId  pulumi.StringPtrInput `pulumi:"publicZoneId"`
}

func (AWSConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AWSConfig)(nil)).Elem()
}

func (i AWSConfigArgs) ToAWSConfigOutput() AWSConfigOutput {
	return i.ToAWSConfigOutputWithContext(context.Background())
}

func (i AWSConfigArgs) ToAWSConfigOutputWithContext(ctx context.Context) AWSConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AWSConfigOutput)
}

func (i AWSConfigArgs) ToAWSConfigPtrOutput() AWSConfigPtrOutput {
	return i.ToAWSConfigPtrOutputWithContext(context.Background())
}

func (i AWSConfigArgs) ToAWSConfigPtrOutputWithContext(ctx context.Context) AWSConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AWSConfigOutput).ToAWSConfigPtrOutputWithContext(ctx)
}

// AWSConfigPtrInput is an input type that accepts AWSConfigArgs, AWSConfigPtr and AWSConfigPtrOutput values.
// You can construct a concrete instance of `AWSConfigPtrInput` via:
//
//	        AWSConfigArgs{...}
//
//	or:
//
//	        nil
type AWSConfigPtrInput interface {
	pulumi.Input

	ToAWSConfigPtrOutput() AWSConfigPtrOutput
	ToAWSConfigPtrOutputWithContext(context.Context) AWSConfigPtrOutput
}

type awsconfigPtrType AWSConfigArgs

func AWSConfigPtr(v *AWSConfigArgs) AWSConfigPtrInput {
	return (*awsconfigPtrType)(v)
}

func (*awsconfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AWSConfig)(nil)).Elem()
}

func (i *awsconfigPtrType) ToAWSConfigPtrOutput() AWSConfigPtrOutput {
	return i.ToAWSConfigPtrOutputWithContext(context.Background())
}

func (i *awsconfigPtrType) ToAWSConfigPtrOutputWithContext(ctx context.Context) AWSConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AWSConfigPtrOutput)
}

type AWSConfigOutput struct{ *pulumi.OutputState }

func (AWSConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AWSConfig)(nil)).Elem()
}

func (o AWSConfigOutput) ToAWSConfigOutput() AWSConfigOutput {
	return o
}

func (o AWSConfigOutput) ToAWSConfigOutputWithContext(ctx context.Context) AWSConfigOutput {
	return o
}

func (o AWSConfigOutput) ToAWSConfigPtrOutput() AWSConfigPtrOutput {
	return o.ToAWSConfigPtrOutputWithContext(context.Background())
}

func (o AWSConfigOutput) ToAWSConfigPtrOutputWithContext(ctx context.Context) AWSConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AWSConfig) *AWSConfig {
		return &v
	}).(AWSConfigPtrOutput)
}

func (o AWSConfigOutput) ProjectDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AWSConfig) *string { return v.ProjectDomain }).(pulumi.StringPtrOutput)
}

func (o AWSConfigOutput) PublicZoneId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AWSConfig) *string { return v.PublicZoneId }).(pulumi.StringPtrOutput)
}

type AWSConfigPtrOutput struct{ *pulumi.OutputState }

func (AWSConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AWSConfig)(nil)).Elem()
}

func (o AWSConfigPtrOutput) ToAWSConfigPtrOutput() AWSConfigPtrOutput {
	return o
}

func (o AWSConfigPtrOutput) ToAWSConfigPtrOutputWithContext(ctx context.Context) AWSConfigPtrOutput {
	return o
}

func (o AWSConfigPtrOutput) Elem() AWSConfigOutput {
	return o.ApplyT(func(v *AWSConfig) AWSConfig {
		if v != nil {
			return *v
		}
		var ret AWSConfig
		return ret
	}).(AWSConfigOutput)
}

func (o AWSConfigPtrOutput) ProjectDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AWSConfig) *string {
		if v == nil {
			return nil
		}
		return v.ProjectDomain
	}).(pulumi.StringPtrOutput)
}

func (o AWSConfigPtrOutput) PublicZoneId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AWSConfig) *string {
		if v == nil {
			return nil
		}
		return v.PublicZoneId
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AWSConfigInput)(nil)).Elem(), AWSConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AWSConfigPtrInput)(nil)).Elem(), AWSConfigArgs{})
	pulumi.RegisterOutputType(AWSConfigOutput{})
	pulumi.RegisterOutputType(AWSConfigPtrOutput{})
}
