// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangscaleway

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-scaleway/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Build struct {
	pulumi.CustomResourceState

	BuildArgs   pulumi.StringMapOutput   `pulumi:"buildArgs"`
	BuildId     pulumi.StringOutput      `pulumi:"buildId"`
	Destination pulumi.StringOutput      `pulumi:"destination"`
	Dockerfile  pulumi.StringPtrOutput   `pulumi:"dockerfile"`
	Image       pulumi.StringOutput      `pulumi:"image"`
	MaxWaitTime pulumi.IntPtrOutput      `pulumi:"maxWaitTime"`
	ProjectId   pulumi.StringOutput      `pulumi:"projectId"`
	Region      pulumi.StringOutput      `pulumi:"region"`
	Source      pulumi.StringOutput      `pulumi:"source"`
	Target      pulumi.StringPtrOutput   `pulumi:"target"`
	Triggers    pulumi.StringArrayOutput `pulumi:"triggers"`
}

// NewBuild registers a new resource with the given unique name, arguments, and options.
func NewBuild(ctx *pulumi.Context,
	name string, args *BuildArgs, opts ...pulumi.ResourceOption) (*Build, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Destination == nil {
		return nil, errors.New("invalid value for required argument 'Destination'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Build
	err := ctx.RegisterResource("defang-scaleway:index:Build", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBuild gets an existing Build resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBuild(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BuildState, opts ...pulumi.ResourceOption) (*Build, error) {
	var resource Build
	err := ctx.ReadResource("defang-scaleway:index:Build", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Build resources.
type buildState struct {
}

type BuildState struct {
}

func (BuildState) ElementType() reflect.Type {
	return reflect.TypeOf((*buildState)(nil)).Elem()
}

type buildArgs struct {
	BuildArgs   map[string]string `pulumi:"buildArgs"`
	Destination string            `pulumi:"destination"`
	Dockerfile  *string           `pulumi:"dockerfile"`
	MaxWaitTime *int              `pulumi:"maxWaitTime"`
	ProjectId   string            `pulumi:"projectId"`
	Region      string            `pulumi:"region"`
	Source      string            `pulumi:"source"`
	Target      *string           `pulumi:"target"`
	Triggers    []string          `pulumi:"triggers"`
}

// The set of arguments for constructing a Build resource.
type BuildArgs struct {
	BuildArgs   pulumi.StringMapInput
	Destination pulumi.StringInput
	Dockerfile  pulumi.StringPtrInput
	MaxWaitTime pulumi.IntPtrInput
	ProjectId   pulumi.StringInput
	Region      pulumi.StringInput
	Source      pulumi.StringInput
	Target      pulumi.StringPtrInput
	Triggers    pulumi.StringArrayInput
}

func (BuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*buildArgs)(nil)).Elem()
}

type BuildInput interface {
	pulumi.Input

	ToBuildOutput() BuildOutput
	ToBuildOutputWithContext(ctx context.Context) BuildOutput
}

func (*Build) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (i *Build) ToBuildOutput() BuildOutput {
	return i.ToBuildOutputWithContext(context.Background())
}

func (i *Build) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildOutput)
}

type BuildOutput struct{ *pulumi.OutputState }

func (BuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (o BuildOutput) ToBuildOutput() BuildOutput {
	return o
}

func (o BuildOutput) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return o
}

func (o BuildOutput) BuildArgs() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Build) pulumi.StringMapOutput { return v.BuildArgs }).(pulumi.StringMapOutput)
}

func (o BuildOutput) BuildId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.BuildId }).(pulumi.StringOutput)
}

func (o BuildOutput) Destination() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Destination }).(pulumi.StringOutput)
}

func (o BuildOutput) Dockerfile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.Dockerfile }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

func (o BuildOutput) MaxWaitTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.IntPtrOutput { return v.MaxWaitTime }).(pulumi.IntPtrOutput)
}

func (o BuildOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

func (o BuildOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o BuildOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

func (o BuildOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.Target }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Triggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Build) pulumi.StringArrayOutput { return v.Triggers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BuildInput)(nil)).Elem(), &Build{})
	pulumi.RegisterOutputType(BuildOutput{})
}
