// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package compose

import (
	"context"
	"reflect"

	"github.com/DefangLabs/pulumi-defang/sdk/go/defang-azure/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type BuildConfig struct {
	Args       map[string]string `pulumi:"args"`
	Context    string            `pulumi:"context"`
	Dockerfile *string           `pulumi:"dockerfile"`
	ShmSize    *string           `pulumi:"shmSize"`
	Target     *string           `pulumi:"target"`
}

// BuildConfigInput is an input type that accepts BuildConfigArgs and BuildConfigOutput values.
// You can construct a concrete instance of `BuildConfigInput` via:
//
//	BuildConfigArgs{...}
type BuildConfigInput interface {
	pulumi.Input

	ToBuildConfigOutput() BuildConfigOutput
	ToBuildConfigOutputWithContext(context.Context) BuildConfigOutput
}

type BuildConfigArgs struct {
	Args       pulumi.StringMapInput `pulumi:"args"`
	Context    pulumi.StringInput    `pulumi:"context"`
	Dockerfile pulumi.StringPtrInput `pulumi:"dockerfile"`
	ShmSize    pulumi.StringPtrInput `pulumi:"shmSize"`
	Target     pulumi.StringPtrInput `pulumi:"target"`
}

func (BuildConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BuildConfig)(nil)).Elem()
}

func (i BuildConfigArgs) ToBuildConfigOutput() BuildConfigOutput {
	return i.ToBuildConfigOutputWithContext(context.Background())
}

func (i BuildConfigArgs) ToBuildConfigOutputWithContext(ctx context.Context) BuildConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildConfigOutput)
}

func (i BuildConfigArgs) ToBuildConfigPtrOutput() BuildConfigPtrOutput {
	return i.ToBuildConfigPtrOutputWithContext(context.Background())
}

func (i BuildConfigArgs) ToBuildConfigPtrOutputWithContext(ctx context.Context) BuildConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildConfigOutput).ToBuildConfigPtrOutputWithContext(ctx)
}

// BuildConfigPtrInput is an input type that accepts BuildConfigArgs, BuildConfigPtr and BuildConfigPtrOutput values.
// You can construct a concrete instance of `BuildConfigPtrInput` via:
//
//	        BuildConfigArgs{...}
//
//	or:
//
//	        nil
type BuildConfigPtrInput interface {
	pulumi.Input

	ToBuildConfigPtrOutput() BuildConfigPtrOutput
	ToBuildConfigPtrOutputWithContext(context.Context) BuildConfigPtrOutput
}

type buildConfigPtrType BuildConfigArgs

func BuildConfigPtr(v *BuildConfigArgs) BuildConfigPtrInput {
	return (*buildConfigPtrType)(v)
}

func (*buildConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BuildConfig)(nil)).Elem()
}

func (i *buildConfigPtrType) ToBuildConfigPtrOutput() BuildConfigPtrOutput {
	return i.ToBuildConfigPtrOutputWithContext(context.Background())
}

func (i *buildConfigPtrType) ToBuildConfigPtrOutputWithContext(ctx context.Context) BuildConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildConfigPtrOutput)
}

type BuildConfigOutput struct{ *pulumi.OutputState }

func (BuildConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BuildConfig)(nil)).Elem()
}

func (o BuildConfigOutput) ToBuildConfigOutput() BuildConfigOutput {
	return o
}

func (o BuildConfigOutput) ToBuildConfigOutputWithContext(ctx context.Context) BuildConfigOutput {
	return o
}

func (o BuildConfigOutput) ToBuildConfigPtrOutput() BuildConfigPtrOutput {
	return o.ToBuildConfigPtrOutputWithContext(context.Background())
}

func (o BuildConfigOutput) ToBuildConfigPtrOutputWithContext(ctx context.Context) BuildConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v BuildConfig) *BuildConfig {
		return &v
	}).(BuildConfigPtrOutput)
}

func (o BuildConfigOutput) Args() pulumi.StringMapOutput {
	return o.ApplyT(func(v BuildConfig) map[string]string { return v.Args }).(pulumi.StringMapOutput)
}

func (o BuildConfigOutput) Context() pulumi.StringOutput {
	return o.ApplyT(func(v BuildConfig) string { return v.Context }).(pulumi.StringOutput)
}

func (o BuildConfigOutput) Dockerfile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BuildConfig) *string { return v.Dockerfile }).(pulumi.StringPtrOutput)
}

func (o BuildConfigOutput) ShmSize() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BuildConfig) *string { return v.ShmSize }).(pulumi.StringPtrOutput)
}

func (o BuildConfigOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v BuildConfig) *string { return v.Target }).(pulumi.StringPtrOutput)
}

type BuildConfigPtrOutput struct{ *pulumi.OutputState }

func (BuildConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BuildConfig)(nil)).Elem()
}

func (o BuildConfigPtrOutput) ToBuildConfigPtrOutput() BuildConfigPtrOutput {
	return o
}

func (o BuildConfigPtrOutput) ToBuildConfigPtrOutputWithContext(ctx context.Context) BuildConfigPtrOutput {
	return o
}

func (o BuildConfigPtrOutput) Elem() BuildConfigOutput {
	return o.ApplyT(func(v *BuildConfig) BuildConfig {
		if v != nil {
			return *v
		}
		var ret BuildConfig
		return ret
	}).(BuildConfigOutput)
}

func (o BuildConfigPtrOutput) Args() pulumi.StringMapOutput {
	return o.ApplyT(func(v *BuildConfig) map[string]string {
		if v == nil {
			return nil
		}
		return v.Args
	}).(pulumi.StringMapOutput)
}

func (o BuildConfigPtrOutput) Context() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BuildConfig) *string {
		if v == nil {
			return nil
		}
		return &v.Context
	}).(pulumi.StringPtrOutput)
}

func (o BuildConfigPtrOutput) Dockerfile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BuildConfig) *string {
		if v == nil {
			return nil
		}
		return v.Dockerfile
	}).(pulumi.StringPtrOutput)
}

func (o BuildConfigPtrOutput) ShmSize() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BuildConfig) *string {
		if v == nil {
			return nil
		}
		return v.ShmSize
	}).(pulumi.StringPtrOutput)
}

func (o BuildConfigPtrOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *BuildConfig) *string {
		if v == nil {
			return nil
		}
		return v.Target
	}).(pulumi.StringPtrOutput)
}

type DeployConfig struct {
	Replicas  *int       `pulumi:"replicas"`
	Resources *Resources `pulumi:"resources"`
}

// DeployConfigInput is an input type that accepts DeployConfigArgs and DeployConfigOutput values.
// You can construct a concrete instance of `DeployConfigInput` via:
//
//	DeployConfigArgs{...}
type DeployConfigInput interface {
	pulumi.Input

	ToDeployConfigOutput() DeployConfigOutput
	ToDeployConfigOutputWithContext(context.Context) DeployConfigOutput
}

type DeployConfigArgs struct {
	Replicas  pulumi.IntPtrInput `pulumi:"replicas"`
	Resources ResourcesPtrInput  `pulumi:"resources"`
}

func (DeployConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DeployConfig)(nil)).Elem()
}

func (i DeployConfigArgs) ToDeployConfigOutput() DeployConfigOutput {
	return i.ToDeployConfigOutputWithContext(context.Background())
}

func (i DeployConfigArgs) ToDeployConfigOutputWithContext(ctx context.Context) DeployConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployConfigOutput)
}

func (i DeployConfigArgs) ToDeployConfigPtrOutput() DeployConfigPtrOutput {
	return i.ToDeployConfigPtrOutputWithContext(context.Background())
}

func (i DeployConfigArgs) ToDeployConfigPtrOutputWithContext(ctx context.Context) DeployConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployConfigOutput).ToDeployConfigPtrOutputWithContext(ctx)
}

// DeployConfigPtrInput is an input type that accepts DeployConfigArgs, DeployConfigPtr and DeployConfigPtrOutput values.
// You can construct a concrete instance of `DeployConfigPtrInput` via:
//
//	        DeployConfigArgs{...}
//
//	or:
//
//	        nil
type DeployConfigPtrInput interface {
	pulumi.Input

	ToDeployConfigPtrOutput() DeployConfigPtrOutput
	ToDeployConfigPtrOutputWithContext(context.Context) DeployConfigPtrOutput
}

type deployConfigPtrType DeployConfigArgs

func DeployConfigPtr(v *DeployConfigArgs) DeployConfigPtrInput {
	return (*deployConfigPtrType)(v)
}

func (*deployConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployConfig)(nil)).Elem()
}

func (i *deployConfigPtrType) ToDeployConfigPtrOutput() DeployConfigPtrOutput {
	return i.ToDeployConfigPtrOutputWithContext(context.Background())
}

func (i *deployConfigPtrType) ToDeployConfigPtrOutputWithContext(ctx context.Context) DeployConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployConfigPtrOutput)
}

type DeployConfigOutput struct{ *pulumi.OutputState }

func (DeployConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DeployConfig)(nil)).Elem()
}

func (o DeployConfigOutput) ToDeployConfigOutput() DeployConfigOutput {
	return o
}

func (o DeployConfigOutput) ToDeployConfigOutputWithContext(ctx context.Context) DeployConfigOutput {
	return o
}

func (o DeployConfigOutput) ToDeployConfigPtrOutput() DeployConfigPtrOutput {
	return o.ToDeployConfigPtrOutputWithContext(context.Background())
}

func (o DeployConfigOutput) ToDeployConfigPtrOutputWithContext(ctx context.Context) DeployConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DeployConfig) *DeployConfig {
		return &v
	}).(DeployConfigPtrOutput)
}

func (o DeployConfigOutput) Replicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DeployConfig) *int { return v.Replicas }).(pulumi.IntPtrOutput)
}

func (o DeployConfigOutput) Resources() ResourcesPtrOutput {
	return o.ApplyT(func(v DeployConfig) *Resources { return v.Resources }).(ResourcesPtrOutput)
}

type DeployConfigPtrOutput struct{ *pulumi.OutputState }

func (DeployConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployConfig)(nil)).Elem()
}

func (o DeployConfigPtrOutput) ToDeployConfigPtrOutput() DeployConfigPtrOutput {
	return o
}

func (o DeployConfigPtrOutput) ToDeployConfigPtrOutputWithContext(ctx context.Context) DeployConfigPtrOutput {
	return o
}

func (o DeployConfigPtrOutput) Elem() DeployConfigOutput {
	return o.ApplyT(func(v *DeployConfig) DeployConfig {
		if v != nil {
			return *v
		}
		var ret DeployConfig
		return ret
	}).(DeployConfigOutput)
}

func (o DeployConfigPtrOutput) Replicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DeployConfig) *int {
		if v == nil {
			return nil
		}
		return v.Replicas
	}).(pulumi.IntPtrOutput)
}

func (o DeployConfigPtrOutput) Resources() ResourcesPtrOutput {
	return o.ApplyT(func(v *DeployConfig) *Resources {
		if v == nil {
			return nil
		}
		return v.Resources
	}).(ResourcesPtrOutput)
}

type HealthCheckConfig struct {
	IntervalSeconds    *int     `pulumi:"intervalSeconds"`
	Retries            *int     `pulumi:"retries"`
	StartPeriodSeconds *int     `pulumi:"startPeriodSeconds"`
	Test               []string `pulumi:"test"`
	TimeoutSeconds     *int     `pulumi:"timeoutSeconds"`
}

// HealthCheckConfigInput is an input type that accepts HealthCheckConfigArgs and HealthCheckConfigOutput values.
// You can construct a concrete instance of `HealthCheckConfigInput` via:
//
//	HealthCheckConfigArgs{...}
type HealthCheckConfigInput interface {
	pulumi.Input

	ToHealthCheckConfigOutput() HealthCheckConfigOutput
	ToHealthCheckConfigOutputWithContext(context.Context) HealthCheckConfigOutput
}

type HealthCheckConfigArgs struct {
	IntervalSeconds    pulumi.IntPtrInput      `pulumi:"intervalSeconds"`
	Retries            pulumi.IntPtrInput      `pulumi:"retries"`
	StartPeriodSeconds pulumi.IntPtrInput      `pulumi:"startPeriodSeconds"`
	Test               pulumi.StringArrayInput `pulumi:"test"`
	TimeoutSeconds     pulumi.IntPtrInput      `pulumi:"timeoutSeconds"`
}

func (HealthCheckConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*HealthCheckConfig)(nil)).Elem()
}

func (i HealthCheckConfigArgs) ToHealthCheckConfigOutput() HealthCheckConfigOutput {
	return i.ToHealthCheckConfigOutputWithContext(context.Background())
}

func (i HealthCheckConfigArgs) ToHealthCheckConfigOutputWithContext(ctx context.Context) HealthCheckConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckConfigOutput)
}

func (i HealthCheckConfigArgs) ToHealthCheckConfigPtrOutput() HealthCheckConfigPtrOutput {
	return i.ToHealthCheckConfigPtrOutputWithContext(context.Background())
}

func (i HealthCheckConfigArgs) ToHealthCheckConfigPtrOutputWithContext(ctx context.Context) HealthCheckConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckConfigOutput).ToHealthCheckConfigPtrOutputWithContext(ctx)
}

// HealthCheckConfigPtrInput is an input type that accepts HealthCheckConfigArgs, HealthCheckConfigPtr and HealthCheckConfigPtrOutput values.
// You can construct a concrete instance of `HealthCheckConfigPtrInput` via:
//
//	        HealthCheckConfigArgs{...}
//
//	or:
//
//	        nil
type HealthCheckConfigPtrInput interface {
	pulumi.Input

	ToHealthCheckConfigPtrOutput() HealthCheckConfigPtrOutput
	ToHealthCheckConfigPtrOutputWithContext(context.Context) HealthCheckConfigPtrOutput
}

type healthCheckConfigPtrType HealthCheckConfigArgs

func HealthCheckConfigPtr(v *HealthCheckConfigArgs) HealthCheckConfigPtrInput {
	return (*healthCheckConfigPtrType)(v)
}

func (*healthCheckConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**HealthCheckConfig)(nil)).Elem()
}

func (i *healthCheckConfigPtrType) ToHealthCheckConfigPtrOutput() HealthCheckConfigPtrOutput {
	return i.ToHealthCheckConfigPtrOutputWithContext(context.Background())
}

func (i *healthCheckConfigPtrType) ToHealthCheckConfigPtrOutputWithContext(ctx context.Context) HealthCheckConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HealthCheckConfigPtrOutput)
}

type HealthCheckConfigOutput struct{ *pulumi.OutputState }

func (HealthCheckConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*HealthCheckConfig)(nil)).Elem()
}

func (o HealthCheckConfigOutput) ToHealthCheckConfigOutput() HealthCheckConfigOutput {
	return o
}

func (o HealthCheckConfigOutput) ToHealthCheckConfigOutputWithContext(ctx context.Context) HealthCheckConfigOutput {
	return o
}

func (o HealthCheckConfigOutput) ToHealthCheckConfigPtrOutput() HealthCheckConfigPtrOutput {
	return o.ToHealthCheckConfigPtrOutputWithContext(context.Background())
}

func (o HealthCheckConfigOutput) ToHealthCheckConfigPtrOutputWithContext(ctx context.Context) HealthCheckConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v HealthCheckConfig) *HealthCheckConfig {
		return &v
	}).(HealthCheckConfigPtrOutput)
}

func (o HealthCheckConfigOutput) IntervalSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HealthCheckConfig) *int { return v.IntervalSeconds }).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigOutput) Retries() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HealthCheckConfig) *int { return v.Retries }).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigOutput) StartPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HealthCheckConfig) *int { return v.StartPeriodSeconds }).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigOutput) Test() pulumi.StringArrayOutput {
	return o.ApplyT(func(v HealthCheckConfig) []string { return v.Test }).(pulumi.StringArrayOutput)
}

func (o HealthCheckConfigOutput) TimeoutSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HealthCheckConfig) *int { return v.TimeoutSeconds }).(pulumi.IntPtrOutput)
}

type HealthCheckConfigPtrOutput struct{ *pulumi.OutputState }

func (HealthCheckConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HealthCheckConfig)(nil)).Elem()
}

func (o HealthCheckConfigPtrOutput) ToHealthCheckConfigPtrOutput() HealthCheckConfigPtrOutput {
	return o
}

func (o HealthCheckConfigPtrOutput) ToHealthCheckConfigPtrOutputWithContext(ctx context.Context) HealthCheckConfigPtrOutput {
	return o
}

func (o HealthCheckConfigPtrOutput) Elem() HealthCheckConfigOutput {
	return o.ApplyT(func(v *HealthCheckConfig) HealthCheckConfig {
		if v != nil {
			return *v
		}
		var ret HealthCheckConfig
		return ret
	}).(HealthCheckConfigOutput)
}

func (o HealthCheckConfigPtrOutput) IntervalSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HealthCheckConfig) *int {
		if v == nil {
			return nil
		}
		return v.IntervalSeconds
	}).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigPtrOutput) Retries() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HealthCheckConfig) *int {
		if v == nil {
			return nil
		}
		return v.Retries
	}).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigPtrOutput) StartPeriodSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HealthCheckConfig) *int {
		if v == nil {
			return nil
		}
		return v.StartPeriodSeconds
	}).(pulumi.IntPtrOutput)
}

func (o HealthCheckConfigPtrOutput) Test() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HealthCheckConfig) []string {
		if v == nil {
			return nil
		}
		return v.Test
	}).(pulumi.StringArrayOutput)
}

func (o HealthCheckConfigPtrOutput) TimeoutSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HealthCheckConfig) *int {
		if v == nil {
			return nil
		}
		return v.TimeoutSeconds
	}).(pulumi.IntPtrOutput)
}

type LlmConfig struct {
}

// LlmConfigInput is an input type that accepts LlmConfigArgs and LlmConfigOutput values.
// You can construct a concrete instance of `LlmConfigInput` via:
//
//	LlmConfigArgs{...}
type LlmConfigInput interface {
	pulumi.Input

	ToLlmConfigOutput() LlmConfigOutput
	ToLlmConfigOutputWithContext(context.Context) LlmConfigOutput
}

type LlmConfigArgs struct {
}

func (LlmConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LlmConfig)(nil)).Elem()
}

func (i LlmConfigArgs) ToLlmConfigOutput() LlmConfigOutput {
	return i.ToLlmConfigOutputWithContext(context.Background())
}

func (i LlmConfigArgs) ToLlmConfigOutputWithContext(ctx context.Context) LlmConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LlmConfigOutput)
}

func (i LlmConfigArgs) ToLlmConfigPtrOutput() LlmConfigPtrOutput {
	return i.ToLlmConfigPtrOutputWithContext(context.Background())
}

func (i LlmConfigArgs) ToLlmConfigPtrOutputWithContext(ctx context.Context) LlmConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LlmConfigOutput).ToLlmConfigPtrOutputWithContext(ctx)
}

// LlmConfigPtrInput is an input type that accepts LlmConfigArgs, LlmConfigPtr and LlmConfigPtrOutput values.
// You can construct a concrete instance of `LlmConfigPtrInput` via:
//
//	        LlmConfigArgs{...}
//
//	or:
//
//	        nil
type LlmConfigPtrInput interface {
	pulumi.Input

	ToLlmConfigPtrOutput() LlmConfigPtrOutput
	ToLlmConfigPtrOutputWithContext(context.Context) LlmConfigPtrOutput
}

type llmConfigPtrType LlmConfigArgs

func LlmConfigPtr(v *LlmConfigArgs) LlmConfigPtrInput {
	return (*llmConfigPtrType)(v)
}

func (*llmConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**LlmConfig)(nil)).Elem()
}

func (i *llmConfigPtrType) ToLlmConfigPtrOutput() LlmConfigPtrOutput {
	return i.ToLlmConfigPtrOutputWithContext(context.Background())
}

func (i *llmConfigPtrType) ToLlmConfigPtrOutputWithContext(ctx context.Context) LlmConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LlmConfigPtrOutput)
}

type LlmConfigOutput struct{ *pulumi.OutputState }

func (LlmConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LlmConfig)(nil)).Elem()
}

func (o LlmConfigOutput) ToLlmConfigOutput() LlmConfigOutput {
	return o
}

func (o LlmConfigOutput) ToLlmConfigOutputWithContext(ctx context.Context) LlmConfigOutput {
	return o
}

func (o LlmConfigOutput) ToLlmConfigPtrOutput() LlmConfigPtrOutput {
	return o.ToLlmConfigPtrOutputWithContext(context.Background())
}

func (o LlmConfigOutput) ToLlmConfigPtrOutputWithContext(ctx context.Context) LlmConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v LlmConfig) *LlmConfig {
		return &v
	}).(LlmConfigPtrOutput)
}

type LlmConfigPtrOutput struct{ *pulumi.OutputState }

func (LlmConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LlmConfig)(nil)).Elem()
}

func (o LlmConfigPtrOutput) ToLlmConfigPtrOutput() LlmConfigPtrOutput {
	return o
}

func (o LlmConfigPtrOutput) ToLlmConfigPtrOutputWithContext(ctx context.Context) LlmConfigPtrOutput {
	return o
}

func (o LlmConfigPtrOutput) Elem() LlmConfigOutput {
	return o.ApplyT(func(v *LlmConfig) LlmConfig {
		if v != nil {
			return *v
		}
		var ret LlmConfig
		return ret
	}).(LlmConfigOutput)
}

type NetworkConfig struct {
	Internal *bool `pulumi:"internal"`
}

// NetworkConfigInput is an input type that accepts NetworkConfigArgs and NetworkConfigOutput values.
// You can construct a concrete instance of `NetworkConfigInput` via:
//
//	NetworkConfigArgs{...}
type NetworkConfigInput interface {
	pulumi.Input

	ToNetworkConfigOutput() NetworkConfigOutput
	ToNetworkConfigOutputWithContext(context.Context) NetworkConfigOutput
}

type NetworkConfigArgs struct {
	Internal pulumi.BoolPtrInput `pulumi:"internal"`
}

func (NetworkConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NetworkConfig)(nil)).Elem()
}

func (i NetworkConfigArgs) ToNetworkConfigOutput() NetworkConfigOutput {
	return i.ToNetworkConfigOutputWithContext(context.Background())
}

func (i NetworkConfigArgs) ToNetworkConfigOutputWithContext(ctx context.Context) NetworkConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkConfigOutput)
}

// NetworkConfigMapInput is an input type that accepts NetworkConfigMap and NetworkConfigMapOutput values.
// You can construct a concrete instance of `NetworkConfigMapInput` via:
//
//	NetworkConfigMap{ "key": NetworkConfigArgs{...} }
type NetworkConfigMapInput interface {
	pulumi.Input

	ToNetworkConfigMapOutput() NetworkConfigMapOutput
	ToNetworkConfigMapOutputWithContext(context.Context) NetworkConfigMapOutput
}

type NetworkConfigMap map[string]NetworkConfigInput

func (NetworkConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]NetworkConfig)(nil)).Elem()
}

func (i NetworkConfigMap) ToNetworkConfigMapOutput() NetworkConfigMapOutput {
	return i.ToNetworkConfigMapOutputWithContext(context.Background())
}

func (i NetworkConfigMap) ToNetworkConfigMapOutputWithContext(ctx context.Context) NetworkConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkConfigMapOutput)
}

type NetworkConfigOutput struct{ *pulumi.OutputState }

func (NetworkConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NetworkConfig)(nil)).Elem()
}

func (o NetworkConfigOutput) ToNetworkConfigOutput() NetworkConfigOutput {
	return o
}

func (o NetworkConfigOutput) ToNetworkConfigOutputWithContext(ctx context.Context) NetworkConfigOutput {
	return o
}

func (o NetworkConfigOutput) Internal() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v NetworkConfig) *bool { return v.Internal }).(pulumi.BoolPtrOutput)
}

type NetworkConfigMapOutput struct{ *pulumi.OutputState }

func (NetworkConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]NetworkConfig)(nil)).Elem()
}

func (o NetworkConfigMapOutput) ToNetworkConfigMapOutput() NetworkConfigMapOutput {
	return o
}

func (o NetworkConfigMapOutput) ToNetworkConfigMapOutputWithContext(ctx context.Context) NetworkConfigMapOutput {
	return o
}

func (o NetworkConfigMapOutput) MapIndex(k pulumi.StringInput) NetworkConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) NetworkConfig {
		return vs[0].(map[string]NetworkConfig)[vs[1].(string)]
	}).(NetworkConfigOutput)
}

type PostgresConfig struct {
	AllowDowntime *bool   `pulumi:"allowDowntime"`
	FromSnapshot  *string `pulumi:"fromSnapshot"`
}

// PostgresConfigInput is an input type that accepts PostgresConfigArgs and PostgresConfigOutput values.
// You can construct a concrete instance of `PostgresConfigInput` via:
//
//	PostgresConfigArgs{...}
type PostgresConfigInput interface {
	pulumi.Input

	ToPostgresConfigOutput() PostgresConfigOutput
	ToPostgresConfigOutputWithContext(context.Context) PostgresConfigOutput
}

type PostgresConfigArgs struct {
	AllowDowntime pulumi.BoolPtrInput   `pulumi:"allowDowntime"`
	FromSnapshot  pulumi.StringPtrInput `pulumi:"fromSnapshot"`
}

func (PostgresConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PostgresConfig)(nil)).Elem()
}

func (i PostgresConfigArgs) ToPostgresConfigOutput() PostgresConfigOutput {
	return i.ToPostgresConfigOutputWithContext(context.Background())
}

func (i PostgresConfigArgs) ToPostgresConfigOutputWithContext(ctx context.Context) PostgresConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresConfigOutput)
}

func (i PostgresConfigArgs) ToPostgresConfigPtrOutput() PostgresConfigPtrOutput {
	return i.ToPostgresConfigPtrOutputWithContext(context.Background())
}

func (i PostgresConfigArgs) ToPostgresConfigPtrOutputWithContext(ctx context.Context) PostgresConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresConfigOutput).ToPostgresConfigPtrOutputWithContext(ctx)
}

// PostgresConfigPtrInput is an input type that accepts PostgresConfigArgs, PostgresConfigPtr and PostgresConfigPtrOutput values.
// You can construct a concrete instance of `PostgresConfigPtrInput` via:
//
//	        PostgresConfigArgs{...}
//
//	or:
//
//	        nil
type PostgresConfigPtrInput interface {
	pulumi.Input

	ToPostgresConfigPtrOutput() PostgresConfigPtrOutput
	ToPostgresConfigPtrOutputWithContext(context.Context) PostgresConfigPtrOutput
}

type postgresConfigPtrType PostgresConfigArgs

func PostgresConfigPtr(v *PostgresConfigArgs) PostgresConfigPtrInput {
	return (*postgresConfigPtrType)(v)
}

func (*postgresConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresConfig)(nil)).Elem()
}

func (i *postgresConfigPtrType) ToPostgresConfigPtrOutput() PostgresConfigPtrOutput {
	return i.ToPostgresConfigPtrOutputWithContext(context.Background())
}

func (i *postgresConfigPtrType) ToPostgresConfigPtrOutputWithContext(ctx context.Context) PostgresConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresConfigPtrOutput)
}

type PostgresConfigOutput struct{ *pulumi.OutputState }

func (PostgresConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PostgresConfig)(nil)).Elem()
}

func (o PostgresConfigOutput) ToPostgresConfigOutput() PostgresConfigOutput {
	return o
}

func (o PostgresConfigOutput) ToPostgresConfigOutputWithContext(ctx context.Context) PostgresConfigOutput {
	return o
}

func (o PostgresConfigOutput) ToPostgresConfigPtrOutput() PostgresConfigPtrOutput {
	return o.ToPostgresConfigPtrOutputWithContext(context.Background())
}

func (o PostgresConfigOutput) ToPostgresConfigPtrOutputWithContext(ctx context.Context) PostgresConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v PostgresConfig) *PostgresConfig {
		return &v
	}).(PostgresConfigPtrOutput)
}

func (o PostgresConfigOutput) AllowDowntime() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PostgresConfig) *bool { return v.AllowDowntime }).(pulumi.BoolPtrOutput)
}

func (o PostgresConfigOutput) FromSnapshot() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PostgresConfig) *string { return v.FromSnapshot }).(pulumi.StringPtrOutput)
}

type PostgresConfigPtrOutput struct{ *pulumi.OutputState }

func (PostgresConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresConfig)(nil)).Elem()
}

func (o PostgresConfigPtrOutput) ToPostgresConfigPtrOutput() PostgresConfigPtrOutput {
	return o
}

func (o PostgresConfigPtrOutput) ToPostgresConfigPtrOutputWithContext(ctx context.Context) PostgresConfigPtrOutput {
	return o
}

func (o PostgresConfigPtrOutput) Elem() PostgresConfigOutput {
	return o.ApplyT(func(v *PostgresConfig) PostgresConfig {
		if v != nil {
			return *v
		}
		var ret PostgresConfig
		return ret
	}).(PostgresConfigOutput)
}

func (o PostgresConfigPtrOutput) AllowDowntime() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PostgresConfig) *bool {
		if v == nil {
			return nil
		}
		return v.AllowDowntime
	}).(pulumi.BoolPtrOutput)
}

func (o PostgresConfigPtrOutput) FromSnapshot() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresConfig) *string {
		if v == nil {
			return nil
		}
		return v.FromSnapshot
	}).(pulumi.StringPtrOutput)
}

type RedisConfig struct {
	AllowDowntime *bool   `pulumi:"allowDowntime"`
	FromSnapshot  *string `pulumi:"fromSnapshot"`
}

// RedisConfigInput is an input type that accepts RedisConfigArgs and RedisConfigOutput values.
// You can construct a concrete instance of `RedisConfigInput` via:
//
//	RedisConfigArgs{...}
type RedisConfigInput interface {
	pulumi.Input

	ToRedisConfigOutput() RedisConfigOutput
	ToRedisConfigOutputWithContext(context.Context) RedisConfigOutput
}

type RedisConfigArgs struct {
	AllowDowntime pulumi.BoolPtrInput   `pulumi:"allowDowntime"`
	FromSnapshot  pulumi.StringPtrInput `pulumi:"fromSnapshot"`
}

func (RedisConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RedisConfig)(nil)).Elem()
}

func (i RedisConfigArgs) ToRedisConfigOutput() RedisConfigOutput {
	return i.ToRedisConfigOutputWithContext(context.Background())
}

func (i RedisConfigArgs) ToRedisConfigOutputWithContext(ctx context.Context) RedisConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedisConfigOutput)
}

func (i RedisConfigArgs) ToRedisConfigPtrOutput() RedisConfigPtrOutput {
	return i.ToRedisConfigPtrOutputWithContext(context.Background())
}

func (i RedisConfigArgs) ToRedisConfigPtrOutputWithContext(ctx context.Context) RedisConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedisConfigOutput).ToRedisConfigPtrOutputWithContext(ctx)
}

// RedisConfigPtrInput is an input type that accepts RedisConfigArgs, RedisConfigPtr and RedisConfigPtrOutput values.
// You can construct a concrete instance of `RedisConfigPtrInput` via:
//
//	        RedisConfigArgs{...}
//
//	or:
//
//	        nil
type RedisConfigPtrInput interface {
	pulumi.Input

	ToRedisConfigPtrOutput() RedisConfigPtrOutput
	ToRedisConfigPtrOutputWithContext(context.Context) RedisConfigPtrOutput
}

type redisConfigPtrType RedisConfigArgs

func RedisConfigPtr(v *RedisConfigArgs) RedisConfigPtrInput {
	return (*redisConfigPtrType)(v)
}

func (*redisConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**RedisConfig)(nil)).Elem()
}

func (i *redisConfigPtrType) ToRedisConfigPtrOutput() RedisConfigPtrOutput {
	return i.ToRedisConfigPtrOutputWithContext(context.Background())
}

func (i *redisConfigPtrType) ToRedisConfigPtrOutputWithContext(ctx context.Context) RedisConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedisConfigPtrOutput)
}

type RedisConfigOutput struct{ *pulumi.OutputState }

func (RedisConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RedisConfig)(nil)).Elem()
}

func (o RedisConfigOutput) ToRedisConfigOutput() RedisConfigOutput {
	return o
}

func (o RedisConfigOutput) ToRedisConfigOutputWithContext(ctx context.Context) RedisConfigOutput {
	return o
}

func (o RedisConfigOutput) ToRedisConfigPtrOutput() RedisConfigPtrOutput {
	return o.ToRedisConfigPtrOutputWithContext(context.Background())
}

func (o RedisConfigOutput) ToRedisConfigPtrOutputWithContext(ctx context.Context) RedisConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v RedisConfig) *RedisConfig {
		return &v
	}).(RedisConfigPtrOutput)
}

func (o RedisConfigOutput) AllowDowntime() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v RedisConfig) *bool { return v.AllowDowntime }).(pulumi.BoolPtrOutput)
}

func (o RedisConfigOutput) FromSnapshot() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RedisConfig) *string { return v.FromSnapshot }).(pulumi.StringPtrOutput)
}

type RedisConfigPtrOutput struct{ *pulumi.OutputState }

func (RedisConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RedisConfig)(nil)).Elem()
}

func (o RedisConfigPtrOutput) ToRedisConfigPtrOutput() RedisConfigPtrOutput {
	return o
}

func (o RedisConfigPtrOutput) ToRedisConfigPtrOutputWithContext(ctx context.Context) RedisConfigPtrOutput {
	return o
}

func (o RedisConfigPtrOutput) Elem() RedisConfigOutput {
	return o.ApplyT(func(v *RedisConfig) RedisConfig {
		if v != nil {
			return *v
		}
		var ret RedisConfig
		return ret
	}).(RedisConfigOutput)
}

func (o RedisConfigPtrOutput) AllowDowntime() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RedisConfig) *bool {
		if v == nil {
			return nil
		}
		return v.AllowDowntime
	}).(pulumi.BoolPtrOutput)
}

func (o RedisConfigPtrOutput) FromSnapshot() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RedisConfig) *string {
		if v == nil {
			return nil
		}
		return v.FromSnapshot
	}).(pulumi.StringPtrOutput)
}

type ResourceConfig struct {
	Cpus   *float64 `pulumi:"cpus"`
	Memory *string  `pulumi:"memory"`
}

// ResourceConfigInput is an input type that accepts ResourceConfigArgs and ResourceConfigOutput values.
// You can construct a concrete instance of `ResourceConfigInput` via:
//
//	ResourceConfigArgs{...}
type ResourceConfigInput interface {
	pulumi.Input

	ToResourceConfigOutput() ResourceConfigOutput
	ToResourceConfigOutputWithContext(context.Context) ResourceConfigOutput
}

type ResourceConfigArgs struct {
	Cpus   pulumi.Float64PtrInput `pulumi:"cpus"`
	Memory pulumi.StringPtrInput  `pulumi:"memory"`
}

func (ResourceConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceConfig)(nil)).Elem()
}

func (i ResourceConfigArgs) ToResourceConfigOutput() ResourceConfigOutput {
	return i.ToResourceConfigOutputWithContext(context.Background())
}

func (i ResourceConfigArgs) ToResourceConfigOutputWithContext(ctx context.Context) ResourceConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceConfigOutput)
}

func (i ResourceConfigArgs) ToResourceConfigPtrOutput() ResourceConfigPtrOutput {
	return i.ToResourceConfigPtrOutputWithContext(context.Background())
}

func (i ResourceConfigArgs) ToResourceConfigPtrOutputWithContext(ctx context.Context) ResourceConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceConfigOutput).ToResourceConfigPtrOutputWithContext(ctx)
}

// ResourceConfigPtrInput is an input type that accepts ResourceConfigArgs, ResourceConfigPtr and ResourceConfigPtrOutput values.
// You can construct a concrete instance of `ResourceConfigPtrInput` via:
//
//	        ResourceConfigArgs{...}
//
//	or:
//
//	        nil
type ResourceConfigPtrInput interface {
	pulumi.Input

	ToResourceConfigPtrOutput() ResourceConfigPtrOutput
	ToResourceConfigPtrOutputWithContext(context.Context) ResourceConfigPtrOutput
}

type resourceConfigPtrType ResourceConfigArgs

func ResourceConfigPtr(v *ResourceConfigArgs) ResourceConfigPtrInput {
	return (*resourceConfigPtrType)(v)
}

func (*resourceConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceConfig)(nil)).Elem()
}

func (i *resourceConfigPtrType) ToResourceConfigPtrOutput() ResourceConfigPtrOutput {
	return i.ToResourceConfigPtrOutputWithContext(context.Background())
}

func (i *resourceConfigPtrType) ToResourceConfigPtrOutputWithContext(ctx context.Context) ResourceConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceConfigPtrOutput)
}

type ResourceConfigOutput struct{ *pulumi.OutputState }

func (ResourceConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ResourceConfig)(nil)).Elem()
}

func (o ResourceConfigOutput) ToResourceConfigOutput() ResourceConfigOutput {
	return o
}

func (o ResourceConfigOutput) ToResourceConfigOutputWithContext(ctx context.Context) ResourceConfigOutput {
	return o
}

func (o ResourceConfigOutput) ToResourceConfigPtrOutput() ResourceConfigPtrOutput {
	return o.ToResourceConfigPtrOutputWithContext(context.Background())
}

func (o ResourceConfigOutput) ToResourceConfigPtrOutputWithContext(ctx context.Context) ResourceConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ResourceConfig) *ResourceConfig {
		return &v
	}).(ResourceConfigPtrOutput)
}

func (o ResourceConfigOutput) Cpus() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v ResourceConfig) *float64 { return v.Cpus }).(pulumi.Float64PtrOutput)
}

func (o ResourceConfigOutput) Memory() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ResourceConfig) *string { return v.Memory }).(pulumi.StringPtrOutput)
}

type ResourceConfigPtrOutput struct{ *pulumi.OutputState }

func (ResourceConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceConfig)(nil)).Elem()
}

func (o ResourceConfigPtrOutput) ToResourceConfigPtrOutput() ResourceConfigPtrOutput {
	return o
}

func (o ResourceConfigPtrOutput) ToResourceConfigPtrOutputWithContext(ctx context.Context) ResourceConfigPtrOutput {
	return o
}

func (o ResourceConfigPtrOutput) Elem() ResourceConfigOutput {
	return o.ApplyT(func(v *ResourceConfig) ResourceConfig {
		if v != nil {
			return *v
		}
		var ret ResourceConfig
		return ret
	}).(ResourceConfigOutput)
}

func (o ResourceConfigPtrOutput) Cpus() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *ResourceConfig) *float64 {
		if v == nil {
			return nil
		}
		return v.Cpus
	}).(pulumi.Float64PtrOutput)
}

func (o ResourceConfigPtrOutput) Memory() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ResourceConfig) *string {
		if v == nil {
			return nil
		}
		return v.Memory
	}).(pulumi.StringPtrOutput)
}

type Resources struct {
	Reservations *ResourceConfig `pulumi:"reservations"`
}

// ResourcesInput is an input type that accepts ResourcesArgs and ResourcesOutput values.
// You can construct a concrete instance of `ResourcesInput` via:
//
//	ResourcesArgs{...}
type ResourcesInput interface {
	pulumi.Input

	ToResourcesOutput() ResourcesOutput
	ToResourcesOutputWithContext(context.Context) ResourcesOutput
}

type ResourcesArgs struct {
	Reservations ResourceConfigPtrInput `pulumi:"reservations"`
}

func (ResourcesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Resources)(nil)).Elem()
}

func (i ResourcesArgs) ToResourcesOutput() ResourcesOutput {
	return i.ToResourcesOutputWithContext(context.Background())
}

func (i ResourcesArgs) ToResourcesOutputWithContext(ctx context.Context) ResourcesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourcesOutput)
}

func (i ResourcesArgs) ToResourcesPtrOutput() ResourcesPtrOutput {
	return i.ToResourcesPtrOutputWithContext(context.Background())
}

func (i ResourcesArgs) ToResourcesPtrOutputWithContext(ctx context.Context) ResourcesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourcesOutput).ToResourcesPtrOutputWithContext(ctx)
}

// ResourcesPtrInput is an input type that accepts ResourcesArgs, ResourcesPtr and ResourcesPtrOutput values.
// You can construct a concrete instance of `ResourcesPtrInput` via:
//
//	        ResourcesArgs{...}
//
//	or:
//
//	        nil
type ResourcesPtrInput interface {
	pulumi.Input

	ToResourcesPtrOutput() ResourcesPtrOutput
	ToResourcesPtrOutputWithContext(context.Context) ResourcesPtrOutput
}

type resourcesPtrType ResourcesArgs

func ResourcesPtr(v *ResourcesArgs) ResourcesPtrInput {
	return (*resourcesPtrType)(v)
}

func (*resourcesPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Resources)(nil)).Elem()
}

func (i *resourcesPtrType) ToResourcesPtrOutput() ResourcesPtrOutput {
	return i.ToResourcesPtrOutputWithContext(context.Background())
}

func (i *resourcesPtrType) ToResourcesPtrOutputWithContext(ctx context.Context) ResourcesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourcesPtrOutput)
}

type ResourcesOutput struct{ *pulumi.OutputState }

func (ResourcesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Resources)(nil)).Elem()
}

func (o ResourcesOutput) ToResourcesOutput() ResourcesOutput {
	return o
}

func (o ResourcesOutput) ToResourcesOutputWithContext(ctx context.Context) ResourcesOutput {
	return o
}

func (o ResourcesOutput) ToResourcesPtrOutput() ResourcesPtrOutput {
	return o.ToResourcesPtrOutputWithContext(context.Background())
}

func (o ResourcesOutput) ToResourcesPtrOutputWithContext(ctx context.Context) ResourcesPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Resources) *Resources {
		return &v
	}).(ResourcesPtrOutput)
}

func (o ResourcesOutput) Reservations() ResourceConfigPtrOutput {
	return o.ApplyT(func(v Resources) *ResourceConfig { return v.Reservations }).(ResourceConfigPtrOutput)
}

type ResourcesPtrOutput struct{ *pulumi.OutputState }

func (ResourcesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resources)(nil)).Elem()
}

func (o ResourcesPtrOutput) ToResourcesPtrOutput() ResourcesPtrOutput {
	return o
}

func (o ResourcesPtrOutput) ToResourcesPtrOutputWithContext(ctx context.Context) ResourcesPtrOutput {
	return o
}

func (o ResourcesPtrOutput) Elem() ResourcesOutput {
	return o.ApplyT(func(v *Resources) Resources {
		if v != nil {
			return *v
		}
		var ret Resources
		return ret
	}).(ResourcesOutput)
}

func (o ResourcesPtrOutput) Reservations() ResourceConfigPtrOutput {
	return o.ApplyT(func(v *Resources) *ResourceConfig {
		if v == nil {
			return nil
		}
		return v.Reservations
	}).(ResourceConfigPtrOutput)
}

type ServiceConfig struct {
	Build       *BuildConfig                    `pulumi:"build"`
	Command     []string                        `pulumi:"command"`
	DependsOn   map[string]ServiceDependency    `pulumi:"dependsOn"`
	Deploy      *DeployConfig                   `pulumi:"deploy"`
	DomainName  *string                         `pulumi:"domainName"`
	Entrypoint  []string                        `pulumi:"entrypoint"`
	Environment map[string]string               `pulumi:"environment"`
	HealthCheck *HealthCheckConfig              `pulumi:"healthCheck"`
	Image       *string                         `pulumi:"image"`
	Llm         *LlmConfig                      `pulumi:"llm"`
	Networks    map[string]ServiceNetworkConfig `pulumi:"networks"`
	Platform    *string                         `pulumi:"platform"`
	Ports       []ServicePortConfig             `pulumi:"ports"`
	Postgres    *PostgresConfig                 `pulumi:"postgres"`
	Redis       *RedisConfig                    `pulumi:"redis"`
	Restart     *string                         `pulumi:"restart"`
}

// ServiceConfigInput is an input type that accepts ServiceConfigArgs and ServiceConfigOutput values.
// You can construct a concrete instance of `ServiceConfigInput` via:
//
//	ServiceConfigArgs{...}
type ServiceConfigInput interface {
	pulumi.Input

	ToServiceConfigOutput() ServiceConfigOutput
	ToServiceConfigOutputWithContext(context.Context) ServiceConfigOutput
}

type ServiceConfigArgs struct {
	Build       BuildConfigPtrInput          `pulumi:"build"`
	Command     pulumi.StringArrayInput      `pulumi:"command"`
	DependsOn   ServiceDependencyMapInput    `pulumi:"dependsOn"`
	Deploy      DeployConfigPtrInput         `pulumi:"deploy"`
	DomainName  pulumi.StringPtrInput        `pulumi:"domainName"`
	Entrypoint  pulumi.StringArrayInput      `pulumi:"entrypoint"`
	Environment pulumi.StringMapInput        `pulumi:"environment"`
	HealthCheck HealthCheckConfigPtrInput    `pulumi:"healthCheck"`
	Image       pulumi.StringPtrInput        `pulumi:"image"`
	Llm         LlmConfigPtrInput            `pulumi:"llm"`
	Networks    ServiceNetworkConfigMapInput `pulumi:"networks"`
	Platform    pulumi.StringPtrInput        `pulumi:"platform"`
	Ports       ServicePortConfigArrayInput  `pulumi:"ports"`
	Postgres    PostgresConfigPtrInput       `pulumi:"postgres"`
	Redis       RedisConfigPtrInput          `pulumi:"redis"`
	Restart     pulumi.StringPtrInput        `pulumi:"restart"`
}

func (ServiceConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceConfig)(nil)).Elem()
}

func (i ServiceConfigArgs) ToServiceConfigOutput() ServiceConfigOutput {
	return i.ToServiceConfigOutputWithContext(context.Background())
}

func (i ServiceConfigArgs) ToServiceConfigOutputWithContext(ctx context.Context) ServiceConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceConfigOutput)
}

// ServiceConfigMapInput is an input type that accepts ServiceConfigMap and ServiceConfigMapOutput values.
// You can construct a concrete instance of `ServiceConfigMapInput` via:
//
//	ServiceConfigMap{ "key": ServiceConfigArgs{...} }
type ServiceConfigMapInput interface {
	pulumi.Input

	ToServiceConfigMapOutput() ServiceConfigMapOutput
	ToServiceConfigMapOutputWithContext(context.Context) ServiceConfigMapOutput
}

type ServiceConfigMap map[string]ServiceConfigInput

func (ServiceConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceConfig)(nil)).Elem()
}

func (i ServiceConfigMap) ToServiceConfigMapOutput() ServiceConfigMapOutput {
	return i.ToServiceConfigMapOutputWithContext(context.Background())
}

func (i ServiceConfigMap) ToServiceConfigMapOutputWithContext(ctx context.Context) ServiceConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceConfigMapOutput)
}

type ServiceConfigOutput struct{ *pulumi.OutputState }

func (ServiceConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceConfig)(nil)).Elem()
}

func (o ServiceConfigOutput) ToServiceConfigOutput() ServiceConfigOutput {
	return o
}

func (o ServiceConfigOutput) ToServiceConfigOutputWithContext(ctx context.Context) ServiceConfigOutput {
	return o
}

func (o ServiceConfigOutput) Build() BuildConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *BuildConfig { return v.Build }).(BuildConfigPtrOutput)
}

func (o ServiceConfigOutput) Command() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ServiceConfig) []string { return v.Command }).(pulumi.StringArrayOutput)
}

func (o ServiceConfigOutput) DependsOn() ServiceDependencyMapOutput {
	return o.ApplyT(func(v ServiceConfig) map[string]ServiceDependency { return v.DependsOn }).(ServiceDependencyMapOutput)
}

func (o ServiceConfigOutput) Deploy() DeployConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *DeployConfig { return v.Deploy }).(DeployConfigPtrOutput)
}

func (o ServiceConfigOutput) DomainName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *string { return v.DomainName }).(pulumi.StringPtrOutput)
}

func (o ServiceConfigOutput) Entrypoint() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ServiceConfig) []string { return v.Entrypoint }).(pulumi.StringArrayOutput)
}

func (o ServiceConfigOutput) Environment() pulumi.StringMapOutput {
	return o.ApplyT(func(v ServiceConfig) map[string]string { return v.Environment }).(pulumi.StringMapOutput)
}

func (o ServiceConfigOutput) HealthCheck() HealthCheckConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *HealthCheckConfig { return v.HealthCheck }).(HealthCheckConfigPtrOutput)
}

func (o ServiceConfigOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o ServiceConfigOutput) Llm() LlmConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *LlmConfig { return v.Llm }).(LlmConfigPtrOutput)
}

func (o ServiceConfigOutput) Networks() ServiceNetworkConfigMapOutput {
	return o.ApplyT(func(v ServiceConfig) map[string]ServiceNetworkConfig { return v.Networks }).(ServiceNetworkConfigMapOutput)
}

func (o ServiceConfigOutput) Platform() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *string { return v.Platform }).(pulumi.StringPtrOutput)
}

func (o ServiceConfigOutput) Ports() ServicePortConfigArrayOutput {
	return o.ApplyT(func(v ServiceConfig) []ServicePortConfig { return v.Ports }).(ServicePortConfigArrayOutput)
}

func (o ServiceConfigOutput) Postgres() PostgresConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *PostgresConfig { return v.Postgres }).(PostgresConfigPtrOutput)
}

func (o ServiceConfigOutput) Redis() RedisConfigPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *RedisConfig { return v.Redis }).(RedisConfigPtrOutput)
}

func (o ServiceConfigOutput) Restart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceConfig) *string { return v.Restart }).(pulumi.StringPtrOutput)
}

type ServiceConfigMapOutput struct{ *pulumi.OutputState }

func (ServiceConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceConfig)(nil)).Elem()
}

func (o ServiceConfigMapOutput) ToServiceConfigMapOutput() ServiceConfigMapOutput {
	return o
}

func (o ServiceConfigMapOutput) ToServiceConfigMapOutputWithContext(ctx context.Context) ServiceConfigMapOutput {
	return o
}

func (o ServiceConfigMapOutput) MapIndex(k pulumi.StringInput) ServiceConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ServiceConfig {
		return vs[0].(map[string]ServiceConfig)[vs[1].(string)]
	}).(ServiceConfigOutput)
}

type ServiceDependency struct {
	Condition *string `pulumi:"condition"`
	Required  *bool   `pulumi:"required"`
}

// ServiceDependencyInput is an input type that accepts ServiceDependencyArgs and ServiceDependencyOutput values.
// You can construct a concrete instance of `ServiceDependencyInput` via:
//
//	ServiceDependencyArgs{...}
type ServiceDependencyInput interface {
	pulumi.Input

	ToServiceDependencyOutput() ServiceDependencyOutput
	ToServiceDependencyOutputWithContext(context.Context) ServiceDependencyOutput
}

type ServiceDependencyArgs struct {
	Condition pulumi.StringPtrInput `pulumi:"condition"`
	Required  pulumi.BoolPtrInput   `pulumi:"required"`
}

func (ServiceDependencyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceDependency)(nil)).Elem()
}

func (i ServiceDependencyArgs) ToServiceDependencyOutput() ServiceDependencyOutput {
	return i.ToServiceDependencyOutputWithContext(context.Background())
}

func (i ServiceDependencyArgs) ToServiceDependencyOutputWithContext(ctx context.Context) ServiceDependencyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceDependencyOutput)
}

// ServiceDependencyMapInput is an input type that accepts ServiceDependencyMap and ServiceDependencyMapOutput values.
// You can construct a concrete instance of `ServiceDependencyMapInput` via:
//
//	ServiceDependencyMap{ "key": ServiceDependencyArgs{...} }
type ServiceDependencyMapInput interface {
	pulumi.Input

	ToServiceDependencyMapOutput() ServiceDependencyMapOutput
	ToServiceDependencyMapOutputWithContext(context.Context) ServiceDependencyMapOutput
}

type ServiceDependencyMap map[string]ServiceDependencyInput

func (ServiceDependencyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceDependency)(nil)).Elem()
}

func (i ServiceDependencyMap) ToServiceDependencyMapOutput() ServiceDependencyMapOutput {
	return i.ToServiceDependencyMapOutputWithContext(context.Background())
}

func (i ServiceDependencyMap) ToServiceDependencyMapOutputWithContext(ctx context.Context) ServiceDependencyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceDependencyMapOutput)
}

type ServiceDependencyOutput struct{ *pulumi.OutputState }

func (ServiceDependencyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceDependency)(nil)).Elem()
}

func (o ServiceDependencyOutput) ToServiceDependencyOutput() ServiceDependencyOutput {
	return o
}

func (o ServiceDependencyOutput) ToServiceDependencyOutputWithContext(ctx context.Context) ServiceDependencyOutput {
	return o
}

func (o ServiceDependencyOutput) Condition() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceDependency) *string { return v.Condition }).(pulumi.StringPtrOutput)
}

func (o ServiceDependencyOutput) Required() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ServiceDependency) *bool { return v.Required }).(pulumi.BoolPtrOutput)
}

type ServiceDependencyMapOutput struct{ *pulumi.OutputState }

func (ServiceDependencyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceDependency)(nil)).Elem()
}

func (o ServiceDependencyMapOutput) ToServiceDependencyMapOutput() ServiceDependencyMapOutput {
	return o
}

func (o ServiceDependencyMapOutput) ToServiceDependencyMapOutputWithContext(ctx context.Context) ServiceDependencyMapOutput {
	return o
}

func (o ServiceDependencyMapOutput) MapIndex(k pulumi.StringInput) ServiceDependencyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ServiceDependency {
		return vs[0].(map[string]ServiceDependency)[vs[1].(string)]
	}).(ServiceDependencyOutput)
}

type ServiceNetworkConfig struct {
	Aliases []string `pulumi:"aliases"`
}

// ServiceNetworkConfigInput is an input type that accepts ServiceNetworkConfigArgs and ServiceNetworkConfigOutput values.
// You can construct a concrete instance of `ServiceNetworkConfigInput` via:
//
//	ServiceNetworkConfigArgs{...}
type ServiceNetworkConfigInput interface {
	pulumi.Input

	ToServiceNetworkConfigOutput() ServiceNetworkConfigOutput
	ToServiceNetworkConfigOutputWithContext(context.Context) ServiceNetworkConfigOutput
}

type ServiceNetworkConfigArgs struct {
	Aliases pulumi.StringArrayInput `pulumi:"aliases"`
}

func (ServiceNetworkConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceNetworkConfig)(nil)).Elem()
}

func (i ServiceNetworkConfigArgs) ToServiceNetworkConfigOutput() ServiceNetworkConfigOutput {
	return i.ToServiceNetworkConfigOutputWithContext(context.Background())
}

func (i ServiceNetworkConfigArgs) ToServiceNetworkConfigOutputWithContext(ctx context.Context) ServiceNetworkConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceNetworkConfigOutput)
}

// ServiceNetworkConfigMapInput is an input type that accepts ServiceNetworkConfigMap and ServiceNetworkConfigMapOutput values.
// You can construct a concrete instance of `ServiceNetworkConfigMapInput` via:
//
//	ServiceNetworkConfigMap{ "key": ServiceNetworkConfigArgs{...} }
type ServiceNetworkConfigMapInput interface {
	pulumi.Input

	ToServiceNetworkConfigMapOutput() ServiceNetworkConfigMapOutput
	ToServiceNetworkConfigMapOutputWithContext(context.Context) ServiceNetworkConfigMapOutput
}

type ServiceNetworkConfigMap map[string]ServiceNetworkConfigInput

func (ServiceNetworkConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceNetworkConfig)(nil)).Elem()
}

func (i ServiceNetworkConfigMap) ToServiceNetworkConfigMapOutput() ServiceNetworkConfigMapOutput {
	return i.ToServiceNetworkConfigMapOutputWithContext(context.Background())
}

func (i ServiceNetworkConfigMap) ToServiceNetworkConfigMapOutputWithContext(ctx context.Context) ServiceNetworkConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceNetworkConfigMapOutput)
}

type ServiceNetworkConfigOutput struct{ *pulumi.OutputState }

func (ServiceNetworkConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceNetworkConfig)(nil)).Elem()
}

func (o ServiceNetworkConfigOutput) ToServiceNetworkConfigOutput() ServiceNetworkConfigOutput {
	return o
}

func (o ServiceNetworkConfigOutput) ToServiceNetworkConfigOutputWithContext(ctx context.Context) ServiceNetworkConfigOutput {
	return o
}

func (o ServiceNetworkConfigOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ServiceNetworkConfig) []string { return v.Aliases }).(pulumi.StringArrayOutput)
}

type ServiceNetworkConfigMapOutput struct{ *pulumi.OutputState }

func (ServiceNetworkConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ServiceNetworkConfig)(nil)).Elem()
}

func (o ServiceNetworkConfigMapOutput) ToServiceNetworkConfigMapOutput() ServiceNetworkConfigMapOutput {
	return o
}

func (o ServiceNetworkConfigMapOutput) ToServiceNetworkConfigMapOutputWithContext(ctx context.Context) ServiceNetworkConfigMapOutput {
	return o
}

func (o ServiceNetworkConfigMapOutput) MapIndex(k pulumi.StringInput) ServiceNetworkConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ServiceNetworkConfig {
		return vs[0].(map[string]ServiceNetworkConfig)[vs[1].(string)]
	}).(ServiceNetworkConfigOutput)
}

type ServicePortConfig struct {
	AppProtocol *string `pulumi:"appProtocol"`
	Mode        *string `pulumi:"mode"`
	Protocol    *string `pulumi:"protocol"`
	Target      int     `pulumi:"target"`
}

// ServicePortConfigInput is an input type that accepts ServicePortConfigArgs and ServicePortConfigOutput values.
// You can construct a concrete instance of `ServicePortConfigInput` via:
//
//	ServicePortConfigArgs{...}
type ServicePortConfigInput interface {
	pulumi.Input

	ToServicePortConfigOutput() ServicePortConfigOutput
	ToServicePortConfigOutputWithContext(context.Context) ServicePortConfigOutput
}

type ServicePortConfigArgs struct {
	AppProtocol pulumi.StringPtrInput `pulumi:"appProtocol"`
	Mode        pulumi.StringPtrInput `pulumi:"mode"`
	Protocol    pulumi.StringPtrInput `pulumi:"protocol"`
	Target      pulumi.IntInput       `pulumi:"target"`
}

func (ServicePortConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServicePortConfig)(nil)).Elem()
}

func (i ServicePortConfigArgs) ToServicePortConfigOutput() ServicePortConfigOutput {
	return i.ToServicePortConfigOutputWithContext(context.Background())
}

func (i ServicePortConfigArgs) ToServicePortConfigOutputWithContext(ctx context.Context) ServicePortConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServicePortConfigOutput)
}

// ServicePortConfigArrayInput is an input type that accepts ServicePortConfigArray and ServicePortConfigArrayOutput values.
// You can construct a concrete instance of `ServicePortConfigArrayInput` via:
//
//	ServicePortConfigArray{ ServicePortConfigArgs{...} }
type ServicePortConfigArrayInput interface {
	pulumi.Input

	ToServicePortConfigArrayOutput() ServicePortConfigArrayOutput
	ToServicePortConfigArrayOutputWithContext(context.Context) ServicePortConfigArrayOutput
}

type ServicePortConfigArray []ServicePortConfigInput

func (ServicePortConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ServicePortConfig)(nil)).Elem()
}

func (i ServicePortConfigArray) ToServicePortConfigArrayOutput() ServicePortConfigArrayOutput {
	return i.ToServicePortConfigArrayOutputWithContext(context.Background())
}

func (i ServicePortConfigArray) ToServicePortConfigArrayOutputWithContext(ctx context.Context) ServicePortConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServicePortConfigArrayOutput)
}

type ServicePortConfigOutput struct{ *pulumi.OutputState }

func (ServicePortConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServicePortConfig)(nil)).Elem()
}

func (o ServicePortConfigOutput) ToServicePortConfigOutput() ServicePortConfigOutput {
	return o
}

func (o ServicePortConfigOutput) ToServicePortConfigOutputWithContext(ctx context.Context) ServicePortConfigOutput {
	return o
}

func (o ServicePortConfigOutput) AppProtocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServicePortConfig) *string { return v.AppProtocol }).(pulumi.StringPtrOutput)
}

func (o ServicePortConfigOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServicePortConfig) *string { return v.Mode }).(pulumi.StringPtrOutput)
}

func (o ServicePortConfigOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServicePortConfig) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

func (o ServicePortConfigOutput) Target() pulumi.IntOutput {
	return o.ApplyT(func(v ServicePortConfig) int { return v.Target }).(pulumi.IntOutput)
}

type ServicePortConfigArrayOutput struct{ *pulumi.OutputState }

func (ServicePortConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ServicePortConfig)(nil)).Elem()
}

func (o ServicePortConfigArrayOutput) ToServicePortConfigArrayOutput() ServicePortConfigArrayOutput {
	return o
}

func (o ServicePortConfigArrayOutput) ToServicePortConfigArrayOutputWithContext(ctx context.Context) ServicePortConfigArrayOutput {
	return o
}

func (o ServicePortConfigArrayOutput) Index(i pulumi.IntInput) ServicePortConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ServicePortConfig {
		return vs[0].([]ServicePortConfig)[vs[1].(int)]
	}).(ServicePortConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BuildConfigInput)(nil)).Elem(), BuildConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*BuildConfigPtrInput)(nil)).Elem(), BuildConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeployConfigInput)(nil)).Elem(), DeployConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeployConfigPtrInput)(nil)).Elem(), DeployConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*HealthCheckConfigInput)(nil)).Elem(), HealthCheckConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*HealthCheckConfigPtrInput)(nil)).Elem(), HealthCheckConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*LlmConfigInput)(nil)).Elem(), LlmConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*LlmConfigPtrInput)(nil)).Elem(), LlmConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkConfigInput)(nil)).Elem(), NetworkConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkConfigMapInput)(nil)).Elem(), NetworkConfigMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresConfigInput)(nil)).Elem(), PostgresConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresConfigPtrInput)(nil)).Elem(), PostgresConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RedisConfigInput)(nil)).Elem(), RedisConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RedisConfigPtrInput)(nil)).Elem(), RedisConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceConfigInput)(nil)).Elem(), ResourceConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceConfigPtrInput)(nil)).Elem(), ResourceConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourcesInput)(nil)).Elem(), ResourcesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ResourcesPtrInput)(nil)).Elem(), ResourcesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceConfigInput)(nil)).Elem(), ServiceConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceConfigMapInput)(nil)).Elem(), ServiceConfigMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceDependencyInput)(nil)).Elem(), ServiceDependencyArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceDependencyMapInput)(nil)).Elem(), ServiceDependencyMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceNetworkConfigInput)(nil)).Elem(), ServiceNetworkConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceNetworkConfigMapInput)(nil)).Elem(), ServiceNetworkConfigMap{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServicePortConfigInput)(nil)).Elem(), ServicePortConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServicePortConfigArrayInput)(nil)).Elem(), ServicePortConfigArray{})
	pulumi.RegisterOutputType(BuildConfigOutput{})
	pulumi.RegisterOutputType(BuildConfigPtrOutput{})
	pulumi.RegisterOutputType(DeployConfigOutput{})
	pulumi.RegisterOutputType(DeployConfigPtrOutput{})
	pulumi.RegisterOutputType(HealthCheckConfigOutput{})
	pulumi.RegisterOutputType(HealthCheckConfigPtrOutput{})
	pulumi.RegisterOutputType(LlmConfigOutput{})
	pulumi.RegisterOutputType(LlmConfigPtrOutput{})
	pulumi.RegisterOutputType(NetworkConfigOutput{})
	pulumi.RegisterOutputType(NetworkConfigMapOutput{})
	pulumi.RegisterOutputType(PostgresConfigOutput{})
	pulumi.RegisterOutputType(PostgresConfigPtrOutput{})
	pulumi.RegisterOutputType(RedisConfigOutput{})
	pulumi.RegisterOutputType(RedisConfigPtrOutput{})
	pulumi.RegisterOutputType(ResourceConfigOutput{})
	pulumi.RegisterOutputType(ResourceConfigPtrOutput{})
	pulumi.RegisterOutputType(ResourcesOutput{})
	pulumi.RegisterOutputType(ResourcesPtrOutput{})
	pulumi.RegisterOutputType(ServiceConfigOutput{})
	pulumi.RegisterOutputType(ServiceConfigMapOutput{})
	pulumi.RegisterOutputType(ServiceDependencyOutput{})
	pulumi.RegisterOutputType(ServiceDependencyMapOutput{})
	pulumi.RegisterOutputType(ServiceNetworkConfigOutput{})
	pulumi.RegisterOutputType(ServiceNetworkConfigMapOutput{})
	pulumi.RegisterOutputType(ServicePortConfigOutput{})
	pulumi.RegisterOutputType(ServicePortConfigArrayOutput{})
}
