// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangaws

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/go/defang-aws/aws"
	"github.com/DefangLabs/pulumi-defang/sdk/go/defang-aws/compose"
	"github.com/DefangLabs/pulumi-defang/sdk/go/defang-aws/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Redis struct {
	pulumi.ResourceState

	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
}

// NewRedis registers a new resource with the given unique name, arguments, and options.
func NewRedis(ctx *pulumi.Context,
	name string, args *RedisArgs, opts ...pulumi.ResourceOption) (*Redis, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Redis
	err := ctx.RegisterRemoteComponentResource("defang-aws:index:Redis", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type redisArgs struct {
	Aws          *aws.SharedInfra            `pulumi:"aws"`
	Deploy       *compose.DeployConfig       `pulumi:"deploy"`
	Environment  map[string]string           `pulumi:"environment"`
	Image        *string                     `pulumi:"image"`
	Ports        []compose.ServicePortConfig `pulumi:"ports"`
	Project_name string                      `pulumi:"project_name"`
	Redis        *compose.RedisConfig        `pulumi:"redis"`
}

// The set of arguments for constructing a Redis resource.
type RedisArgs struct {
	Aws          aws.SharedInfraPtrInput
	Deploy       compose.DeployConfigPtrInput
	Environment  pulumi.StringMapInput
	Image        *string
	Ports        compose.ServicePortConfigArrayInput
	Project_name string
	Redis        compose.RedisConfigPtrInput
}

func (RedisArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*redisArgs)(nil)).Elem()
}

type RedisInput interface {
	pulumi.Input

	ToRedisOutput() RedisOutput
	ToRedisOutputWithContext(ctx context.Context) RedisOutput
}

func (*Redis) ElementType() reflect.Type {
	return reflect.TypeOf((**Redis)(nil)).Elem()
}

func (i *Redis) ToRedisOutput() RedisOutput {
	return i.ToRedisOutputWithContext(context.Background())
}

func (i *Redis) ToRedisOutputWithContext(ctx context.Context) RedisOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RedisOutput)
}

type RedisOutput struct{ *pulumi.OutputState }

func (RedisOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Redis)(nil)).Elem()
}

func (o RedisOutput) ToRedisOutput() RedisOutput {
	return o
}

func (o RedisOutput) ToRedisOutputWithContext(ctx context.Context) RedisOutput {
	return o
}

func (o RedisOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Redis) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RedisInput)(nil)).Elem(), &Redis{})
	pulumi.RegisterOutputType(RedisOutput{})
}
