// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangazure

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-azure/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ACRImageBuild struct {
	pulumi.CustomResourceState

	ContextPath        pulumi.StringOutput      `pulumi:"contextPath"`
	EncodedTaskContent pulumi.StringOutput      `pulumi:"encodedTaskContent"`
	Image              pulumi.StringOutput      `pulumi:"image"`
	ImageName          pulumi.StringOutput      `pulumi:"imageName"`
	LoginServer        pulumi.StringOutput      `pulumi:"loginServer"`
	MaxWaitTime        pulumi.IntPtrOutput      `pulumi:"maxWaitTime"`
	RegistryName       pulumi.StringOutput      `pulumi:"registryName"`
	ResourceGroupName  pulumi.StringOutput      `pulumi:"resourceGroupName"`
	RunId              pulumi.StringOutput      `pulumi:"runId"`
	SubscriptionId     pulumi.StringOutput      `pulumi:"subscriptionId"`
	TaskName           pulumi.StringOutput      `pulumi:"taskName"`
	Triggers           pulumi.StringArrayOutput `pulumi:"triggers"`
}

// NewACRImageBuild registers a new resource with the given unique name, arguments, and options.
func NewACRImageBuild(ctx *pulumi.Context,
	name string, args *ACRImageBuildArgs, opts ...pulumi.ResourceOption) (*ACRImageBuild, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ContextPath == nil {
		return nil, errors.New("invalid value for required argument 'ContextPath'")
	}
	if args.EncodedTaskContent == nil {
		return nil, errors.New("invalid value for required argument 'EncodedTaskContent'")
	}
	if args.ImageName == nil {
		return nil, errors.New("invalid value for required argument 'ImageName'")
	}
	if args.LoginServer == nil {
		return nil, errors.New("invalid value for required argument 'LoginServer'")
	}
	if args.RegistryName == nil {
		return nil, errors.New("invalid value for required argument 'RegistryName'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	if args.SubscriptionId == nil {
		return nil, errors.New("invalid value for required argument 'SubscriptionId'")
	}
	if args.TaskName == nil {
		return nil, errors.New("invalid value for required argument 'TaskName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ACRImageBuild
	err := ctx.RegisterResource("defang-azure:index:ACRImageBuild", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetACRImageBuild gets an existing ACRImageBuild resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetACRImageBuild(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ACRImageBuildState, opts ...pulumi.ResourceOption) (*ACRImageBuild, error) {
	var resource ACRImageBuild
	err := ctx.ReadResource("defang-azure:index:ACRImageBuild", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ACRImageBuild resources.
type acrimageBuildState struct {
}

type ACRImageBuildState struct {
}

func (ACRImageBuildState) ElementType() reflect.Type {
	return reflect.TypeOf((*acrimageBuildState)(nil)).Elem()
}

type acrimageBuildArgs struct {
	ContextPath        string   `pulumi:"contextPath"`
	EncodedTaskContent string   `pulumi:"encodedTaskContent"`
	ImageName          string   `pulumi:"imageName"`
	LoginServer        string   `pulumi:"loginServer"`
	MaxWaitTime        *int     `pulumi:"maxWaitTime"`
	RegistryName       string   `pulumi:"registryName"`
	ResourceGroupName  string   `pulumi:"resourceGroupName"`
	SubscriptionId     string   `pulumi:"subscriptionId"`
	TaskName           string   `pulumi:"taskName"`
	Triggers           []string `pulumi:"triggers"`
}

// The set of arguments for constructing a ACRImageBuild resource.
type ACRImageBuildArgs struct {
	ContextPath        pulumi.StringInput
	EncodedTaskContent pulumi.StringInput
	ImageName          pulumi.StringInput
	LoginServer        pulumi.StringInput
	MaxWaitTime        pulumi.IntPtrInput
	RegistryName       pulumi.StringInput
	ResourceGroupName  pulumi.StringInput
	SubscriptionId     pulumi.StringInput
	TaskName           pulumi.StringInput
	Triggers           pulumi.StringArrayInput
}

func (ACRImageBuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*acrimageBuildArgs)(nil)).Elem()
}

type ACRImageBuildInput interface {
	pulumi.Input

	ToACRImageBuildOutput() ACRImageBuildOutput
	ToACRImageBuildOutputWithContext(ctx context.Context) ACRImageBuildOutput
}

func (*ACRImageBuild) ElementType() reflect.Type {
	return reflect.TypeOf((**ACRImageBuild)(nil)).Elem()
}

func (i *ACRImageBuild) ToACRImageBuildOutput() ACRImageBuildOutput {
	return i.ToACRImageBuildOutputWithContext(context.Background())
}

func (i *ACRImageBuild) ToACRImageBuildOutputWithContext(ctx context.Context) ACRImageBuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ACRImageBuildOutput)
}

type ACRImageBuildOutput struct{ *pulumi.OutputState }

func (ACRImageBuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ACRImageBuild)(nil)).Elem()
}

func (o ACRImageBuildOutput) ToACRImageBuildOutput() ACRImageBuildOutput {
	return o
}

func (o ACRImageBuildOutput) ToACRImageBuildOutputWithContext(ctx context.Context) ACRImageBuildOutput {
	return o
}

func (o ACRImageBuildOutput) ContextPath() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.ContextPath }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) EncodedTaskContent() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.EncodedTaskContent }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) ImageName() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.ImageName }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) LoginServer() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.LoginServer }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) MaxWaitTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.IntPtrOutput { return v.MaxWaitTime }).(pulumi.IntPtrOutput)
}

func (o ACRImageBuildOutput) RegistryName() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.RegistryName }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.ResourceGroupName }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.RunId }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.SubscriptionId }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) TaskName() pulumi.StringOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringOutput { return v.TaskName }).(pulumi.StringOutput)
}

func (o ACRImageBuildOutput) Triggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ACRImageBuild) pulumi.StringArrayOutput { return v.Triggers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ACRImageBuildInput)(nil)).Elem(), &ACRImageBuild{})
	pulumi.RegisterOutputType(ACRImageBuildOutput{})
}
