// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defangazure

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-azure/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Build struct {
	pulumi.CustomResourceState

	ContextPath        pulumi.StringOutput      `pulumi:"contextPath"`
	EncodedTaskContent pulumi.StringOutput      `pulumi:"encodedTaskContent"`
	Image              pulumi.StringOutput      `pulumi:"image"`
	ImageName          pulumi.StringOutput      `pulumi:"imageName"`
	LoginServer        pulumi.StringOutput      `pulumi:"loginServer"`
	MaxWaitTime        pulumi.IntPtrOutput      `pulumi:"maxWaitTime"`
	RegistryName       pulumi.StringOutput      `pulumi:"registryName"`
	ResourceGroupName  pulumi.StringOutput      `pulumi:"resourceGroupName"`
	RunId              pulumi.StringOutput      `pulumi:"runId"`
	SubscriptionId     pulumi.StringOutput      `pulumi:"subscriptionId"`
	TaskName           pulumi.StringOutput      `pulumi:"taskName"`
	Triggers           pulumi.StringArrayOutput `pulumi:"triggers"`
}

// NewBuild registers a new resource with the given unique name, arguments, and options.
func NewBuild(ctx *pulumi.Context,
	name string, args *BuildArgs, opts ...pulumi.ResourceOption) (*Build, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ContextPath == nil {
		return nil, errors.New("invalid value for required argument 'ContextPath'")
	}
	if args.EncodedTaskContent == nil {
		return nil, errors.New("invalid value for required argument 'EncodedTaskContent'")
	}
	if args.ImageName == nil {
		return nil, errors.New("invalid value for required argument 'ImageName'")
	}
	if args.LoginServer == nil {
		return nil, errors.New("invalid value for required argument 'LoginServer'")
	}
	if args.RegistryName == nil {
		return nil, errors.New("invalid value for required argument 'RegistryName'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	if args.SubscriptionId == nil {
		return nil, errors.New("invalid value for required argument 'SubscriptionId'")
	}
	if args.TaskName == nil {
		return nil, errors.New("invalid value for required argument 'TaskName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Build
	err := ctx.RegisterResource("defang-azure:index:Build", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBuild gets an existing Build resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBuild(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BuildState, opts ...pulumi.ResourceOption) (*Build, error) {
	var resource Build
	err := ctx.ReadResource("defang-azure:index:Build", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Build resources.
type buildState struct {
}

type BuildState struct {
}

func (BuildState) ElementType() reflect.Type {
	return reflect.TypeOf((*buildState)(nil)).Elem()
}

type buildArgs struct {
	ContextPath        string   `pulumi:"contextPath"`
	EncodedTaskContent string   `pulumi:"encodedTaskContent"`
	ImageName          string   `pulumi:"imageName"`
	LoginServer        string   `pulumi:"loginServer"`
	MaxWaitTime        *int     `pulumi:"maxWaitTime"`
	RegistryName       string   `pulumi:"registryName"`
	ResourceGroupName  string   `pulumi:"resourceGroupName"`
	SubscriptionId     string   `pulumi:"subscriptionId"`
	TaskName           string   `pulumi:"taskName"`
	Triggers           []string `pulumi:"triggers"`
}

// The set of arguments for constructing a Build resource.
type BuildArgs struct {
	ContextPath        pulumi.StringInput
	EncodedTaskContent pulumi.StringInput
	ImageName          pulumi.StringInput
	LoginServer        pulumi.StringInput
	MaxWaitTime        pulumi.IntPtrInput
	RegistryName       pulumi.StringInput
	ResourceGroupName  pulumi.StringInput
	SubscriptionId     pulumi.StringInput
	TaskName           pulumi.StringInput
	Triggers           pulumi.StringArrayInput
}

func (BuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*buildArgs)(nil)).Elem()
}

type BuildInput interface {
	pulumi.Input

	ToBuildOutput() BuildOutput
	ToBuildOutputWithContext(ctx context.Context) BuildOutput
}

func (*Build) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (i *Build) ToBuildOutput() BuildOutput {
	return i.ToBuildOutputWithContext(context.Background())
}

func (i *Build) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildOutput)
}

type BuildOutput struct{ *pulumi.OutputState }

func (BuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (o BuildOutput) ToBuildOutput() BuildOutput {
	return o
}

func (o BuildOutput) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return o
}

func (o BuildOutput) ContextPath() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ContextPath }).(pulumi.StringOutput)
}

func (o BuildOutput) EncodedTaskContent() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.EncodedTaskContent }).(pulumi.StringOutput)
}

func (o BuildOutput) Image() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Image }).(pulumi.StringOutput)
}

func (o BuildOutput) ImageName() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ImageName }).(pulumi.StringOutput)
}

func (o BuildOutput) LoginServer() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.LoginServer }).(pulumi.StringOutput)
}

func (o BuildOutput) MaxWaitTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.IntPtrOutput { return v.MaxWaitTime }).(pulumi.IntPtrOutput)
}

func (o BuildOutput) RegistryName() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.RegistryName }).(pulumi.StringOutput)
}

func (o BuildOutput) ResourceGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ResourceGroupName }).(pulumi.StringOutput)
}

func (o BuildOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.RunId }).(pulumi.StringOutput)
}

func (o BuildOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.SubscriptionId }).(pulumi.StringOutput)
}

func (o BuildOutput) TaskName() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.TaskName }).(pulumi.StringOutput)
}

func (o BuildOutput) Triggers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Build) pulumi.StringArrayOutput { return v.Triggers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BuildInput)(nil)).Elem(), &Build{})
	pulumi.RegisterOutputType(BuildOutput{})
}
