name: NodeJS Build
description: Build NodeJS project
inputs:
  node-version:
    description: "NodeJS version"
    default: "16" # matches the version in shell.nix and package.json
  cache-dependency-path:
    description: "Path to dependency lock file"
    required: true
  working-directory:
    description: "Working directory"
    required: true
  registry-url:
    description: "Registry URL"
    default: "https://registry.npmjs.org"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
        registry-url: ${{ inputs.registry-url }}
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    #- run: npm test
    #  working-directory: ${{ inputs.working-directory }}
