// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defanggcp

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-gcp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Build struct {
	pulumi.CustomResourceState

	BuildId        pulumi.StringOutput      `pulumi:"buildId"`
	DiskSizeGb     pulumi.IntPtrOutput      `pulumi:"diskSizeGb"`
	ImageDigest    pulumi.StringOutput      `pulumi:"imageDigest"`
	Images         pulumi.StringArrayOutput `pulumi:"images"`
	Location       pulumi.StringOutput      `pulumi:"location"`
	MachineType    pulumi.StringPtrOutput   `pulumi:"machineType"`
	MaxWaitTime    pulumi.IntPtrOutput      `pulumi:"maxWaitTime"`
	ProjectId      pulumi.StringOutput      `pulumi:"projectId"`
	ServiceAccount pulumi.StringPtrOutput   `pulumi:"serviceAccount"`
	Source         pulumi.StringOutput      `pulumi:"source"`
	SourceDigest   pulumi.StringPtrOutput   `pulumi:"sourceDigest"`
	Steps          pulumi.StringOutput      `pulumi:"steps"`
	Substitutions  pulumi.StringMapOutput   `pulumi:"substitutions"`
	Tags           pulumi.StringArrayOutput `pulumi:"tags"`
}

// NewBuild registers a new resource with the given unique name, arguments, and options.
func NewBuild(ctx *pulumi.Context,
	name string, args *BuildArgs, opts ...pulumi.ResourceOption) (*Build, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	if args.Steps == nil {
		return nil, errors.New("invalid value for required argument 'Steps'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"images[*]",
		"location",
		"projectId",
		"serviceAccount",
		"source",
		"sourceDigest",
		"steps",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Build
	err := ctx.RegisterResource("defang-gcp:index:Build", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBuild gets an existing Build resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBuild(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BuildState, opts ...pulumi.ResourceOption) (*Build, error) {
	var resource Build
	err := ctx.ReadResource("defang-gcp:index:Build", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Build resources.
type buildState struct {
}

type BuildState struct {
}

func (BuildState) ElementType() reflect.Type {
	return reflect.TypeOf((*buildState)(nil)).Elem()
}

type buildArgs struct {
	DiskSizeGb     *int              `pulumi:"diskSizeGb"`
	Images         []string          `pulumi:"images"`
	Location       string            `pulumi:"location"`
	MachineType    *string           `pulumi:"machineType"`
	MaxWaitTime    *int              `pulumi:"maxWaitTime"`
	ProjectId      string            `pulumi:"projectId"`
	ServiceAccount *string           `pulumi:"serviceAccount"`
	Source         string            `pulumi:"source"`
	SourceDigest   *string           `pulumi:"sourceDigest"`
	Steps          string            `pulumi:"steps"`
	Substitutions  map[string]string `pulumi:"substitutions"`
	Tags           []string          `pulumi:"tags"`
}

// The set of arguments for constructing a Build resource.
type BuildArgs struct {
	DiskSizeGb     pulumi.IntPtrInput
	Images         pulumi.StringArrayInput
	Location       pulumi.StringInput
	MachineType    pulumi.StringPtrInput
	MaxWaitTime    pulumi.IntPtrInput
	ProjectId      pulumi.StringInput
	ServiceAccount pulumi.StringPtrInput
	Source         pulumi.StringInput
	SourceDigest   pulumi.StringPtrInput
	Steps          pulumi.StringInput
	Substitutions  pulumi.StringMapInput
	Tags           pulumi.StringArrayInput
}

func (BuildArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*buildArgs)(nil)).Elem()
}

type BuildInput interface {
	pulumi.Input

	ToBuildOutput() BuildOutput
	ToBuildOutputWithContext(ctx context.Context) BuildOutput
}

func (*Build) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (i *Build) ToBuildOutput() BuildOutput {
	return i.ToBuildOutputWithContext(context.Background())
}

func (i *Build) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuildOutput)
}

type BuildOutput struct{ *pulumi.OutputState }

func (BuildOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Build)(nil)).Elem()
}

func (o BuildOutput) ToBuildOutput() BuildOutput {
	return o
}

func (o BuildOutput) ToBuildOutputWithContext(ctx context.Context) BuildOutput {
	return o
}

func (o BuildOutput) BuildId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.BuildId }).(pulumi.StringOutput)
}

func (o BuildOutput) DiskSizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.IntPtrOutput { return v.DiskSizeGb }).(pulumi.IntPtrOutput)
}

func (o BuildOutput) ImageDigest() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ImageDigest }).(pulumi.StringOutput)
}

func (o BuildOutput) Images() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Build) pulumi.StringArrayOutput { return v.Images }).(pulumi.StringArrayOutput)
}

func (o BuildOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

func (o BuildOutput) MachineType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.MachineType }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) MaxWaitTime() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.IntPtrOutput { return v.MaxWaitTime }).(pulumi.IntPtrOutput)
}

func (o BuildOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

func (o BuildOutput) ServiceAccount() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.ServiceAccount }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

func (o BuildOutput) SourceDigest() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Build) pulumi.StringPtrOutput { return v.SourceDigest }).(pulumi.StringPtrOutput)
}

func (o BuildOutput) Steps() pulumi.StringOutput {
	return o.ApplyT(func(v *Build) pulumi.StringOutput { return v.Steps }).(pulumi.StringOutput)
}

func (o BuildOutput) Substitutions() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Build) pulumi.StringMapOutput { return v.Substitutions }).(pulumi.StringMapOutput)
}

func (o BuildOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Build) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*BuildInput)(nil)).Elem(), &Build{})
	pulumi.RegisterOutputType(BuildOutput{})
}
