// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defanggcp

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-gcp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Removes the VPC network peering left behind by an abandoned Service Networking connection. Creating it does nothing; deleting it calls compute.networks.removePeering, which is the only delete GCP honours while the service producer is still releasing its resources.
type PeeringCleanup struct {
	pulumi.CustomResourceState

	// The VPC to remove peerings from: a name, an id or a self-link.
	Network pulumi.StringOutput `pulumi:"network"`
	// The GCP project that holds the network.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
}

// NewPeeringCleanup registers a new resource with the given unique name, arguments, and options.
func NewPeeringCleanup(ctx *pulumi.Context,
	name string, args *PeeringCleanupArgs, opts ...pulumi.ResourceOption) (*PeeringCleanup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Network == nil {
		return nil, errors.New("invalid value for required argument 'Network'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"network",
		"projectId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PeeringCleanup
	err := ctx.RegisterResource("defang-gcp:index:PeeringCleanup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPeeringCleanup gets an existing PeeringCleanup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPeeringCleanup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PeeringCleanupState, opts ...pulumi.ResourceOption) (*PeeringCleanup, error) {
	var resource PeeringCleanup
	err := ctx.ReadResource("defang-gcp:index:PeeringCleanup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PeeringCleanup resources.
type peeringCleanupState struct {
}

type PeeringCleanupState struct {
}

func (PeeringCleanupState) ElementType() reflect.Type {
	return reflect.TypeOf((*peeringCleanupState)(nil)).Elem()
}

type peeringCleanupArgs struct {
	// The VPC to remove peerings from: a name, an id or a self-link.
	Network string `pulumi:"network"`
	// The GCP project that holds the network.
	ProjectId string `pulumi:"projectId"`
}

// The set of arguments for constructing a PeeringCleanup resource.
type PeeringCleanupArgs struct {
	// The VPC to remove peerings from: a name, an id or a self-link.
	Network pulumi.StringInput
	// The GCP project that holds the network.
	ProjectId pulumi.StringInput
}

func (PeeringCleanupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*peeringCleanupArgs)(nil)).Elem()
}

type PeeringCleanupInput interface {
	pulumi.Input

	ToPeeringCleanupOutput() PeeringCleanupOutput
	ToPeeringCleanupOutputWithContext(ctx context.Context) PeeringCleanupOutput
}

func (*PeeringCleanup) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringCleanup)(nil)).Elem()
}

func (i *PeeringCleanup) ToPeeringCleanupOutput() PeeringCleanupOutput {
	return i.ToPeeringCleanupOutputWithContext(context.Background())
}

func (i *PeeringCleanup) ToPeeringCleanupOutputWithContext(ctx context.Context) PeeringCleanupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringCleanupOutput)
}

type PeeringCleanupOutput struct{ *pulumi.OutputState }

func (PeeringCleanupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringCleanup)(nil)).Elem()
}

func (o PeeringCleanupOutput) ToPeeringCleanupOutput() PeeringCleanupOutput {
	return o
}

func (o PeeringCleanupOutput) ToPeeringCleanupOutputWithContext(ctx context.Context) PeeringCleanupOutput {
	return o
}

// The VPC to remove peerings from: a name, an id or a self-link.
func (o PeeringCleanupOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringCleanup) pulumi.StringOutput { return v.Network }).(pulumi.StringOutput)
}

// The GCP project that holds the network.
func (o PeeringCleanupOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringCleanup) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PeeringCleanupInput)(nil)).Elem(), &PeeringCleanup{})
	pulumi.RegisterOutputType(PeeringCleanupOutput{})
}
