// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package defanggcp

import (
	"context"
	"reflect"

	"errors"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-gcp/compose"
	"github.com/DefangLabs/pulumi-defang/sdk/v2/go/defang-gcp/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Service struct {
	pulumi.ResourceState

	Endpoint            pulumi.StringOutput `pulumi:"endpoint"`
	ServiceAccountEmail pulumi.StringOutput `pulumi:"serviceAccountEmail"`
}

// NewService registers a new resource with the given unique name, arguments, and options.
func NewService(ctx *pulumi.Context,
	name string, args *ServiceArgs, opts ...pulumi.ResourceOption) (*Service, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Image == nil {
		return nil, errors.New("invalid value for required argument 'Image'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Service
	err := ctx.RegisterRemoteComponentResource("defang-gcp:index:Service", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type serviceArgs struct {
	Command             []string                             `pulumi:"command"`
	ContainerName       *string                              `pulumi:"containerName"`
	DependsOn           map[string]compose.ServiceDependency `pulumi:"dependsOn"`
	Deploy              *compose.DeployConfig                `pulumi:"deploy"`
	DomainName          *string                              `pulumi:"domainName"`
	Entrypoint          []string                             `pulumi:"entrypoint"`
	Environment         map[string]string                    `pulumi:"environment"`
	HealthCheck         *compose.HealthCheckConfig           `pulumi:"healthCheck"`
	Image               string                               `pulumi:"image"`
	Llm                 *compose.LlmConfig                   `pulumi:"llm"`
	Platform            *string                              `pulumi:"platform"`
	Ports               []compose.ServicePortConfig          `pulumi:"ports"`
	ProjectName         string                               `pulumi:"projectName"`
	ServiceAccountEmail *string                              `pulumi:"serviceAccountEmail"`
	Sidecars            map[string]compose.ServiceConfig     `pulumi:"sidecars"`
	StopGracePeriod     *string                              `pulumi:"stopGracePeriod"`
	Triggers            map[string]string                    `pulumi:"triggers"`
	Volumes             []compose.ServiceVolumeConfig        `pulumi:"volumes"`
	VolumesFrom         []string                             `pulumi:"volumesFrom"`
	WorkingDir          *string                              `pulumi:"workingDir"`
}

// The set of arguments for constructing a Service resource.
type ServiceArgs struct {
	Command             pulumi.StringArrayInput
	ContainerName       *string
	DependsOn           compose.ServiceDependencyMapInput
	Deploy              compose.DeployConfigPtrInput
	DomainName          *string
	Entrypoint          pulumi.StringArrayInput
	Environment         pulumi.StringMapInput
	HealthCheck         compose.HealthCheckConfigPtrInput
	Image               pulumi.StringInput
	Llm                 compose.LlmConfigPtrInput
	Platform            *string
	Ports               compose.ServicePortConfigArrayInput
	ProjectName         string
	ServiceAccountEmail pulumi.StringPtrInput
	Sidecars            compose.ServiceConfigMapInput
	StopGracePeriod     *string
	Triggers            pulumi.StringMapInput
	Volumes             compose.ServiceVolumeConfigArrayInput
	VolumesFrom         pulumi.StringArrayInput
	WorkingDir          *string
}

func (ServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceArgs)(nil)).Elem()
}

type ServiceInput interface {
	pulumi.Input

	ToServiceOutput() ServiceOutput
	ToServiceOutputWithContext(ctx context.Context) ServiceOutput
}

func (*Service) ElementType() reflect.Type {
	return reflect.TypeOf((**Service)(nil)).Elem()
}

func (i *Service) ToServiceOutput() ServiceOutput {
	return i.ToServiceOutputWithContext(context.Background())
}

func (i *Service) ToServiceOutputWithContext(ctx context.Context) ServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceOutput)
}

type ServiceOutput struct{ *pulumi.OutputState }

func (ServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Service)(nil)).Elem()
}

func (o ServiceOutput) ToServiceOutput() ServiceOutput {
	return o
}

func (o ServiceOutput) ToServiceOutputWithContext(ctx context.Context) ServiceOutput {
	return o
}

func (o ServiceOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Service) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

func (o ServiceOutput) ServiceAccountEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *Service) pulumi.StringOutput { return v.ServiceAccountEmail }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceInput)(nil)).Elem(), &Service{})
	pulumi.RegisterOutputType(ServiceOutput{})
}
