on:
  pull_request:
    paths-ignore:
      - docs
      - .devcontainer
      - examples

jobs:
  build_sdks:
    name: Build SDKs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
        - nodejs
        - python
        - dotnet
        - go
        provider:
        - aws
        - gcp
        - azure

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Setup and build SDK
      uses: ./.github/actions/build-sdk
      with:
        language: ${{ matrix.language }}
        provider: defang-${{ matrix.provider }}

    - name: Check clean sdks working tree
      run: |
        git update-index -q --refresh
        if ! git diff-index --quiet HEAD -- sdks/; then
          >&2 echo "error: sdks directory is not clean, aborting!"
          git status sdks/
          git diff sdks/
          exit 1
        fi

    - name: Build Example
      run: make example_${{ matrix.provider }}_${{ matrix.language }}

    - name: Check clean examples working tree
      run: |
        git update-index -q --refresh
        if ! git diff-index --quiet HEAD -- examples/; then
            >&2 echo "error: examples directory is not clean, aborting!"
            git status examples/
            git diff examples/
            exit 1
        fi
