on:
  pull_request:
    paths-ignore:
      - docs
      - .devcontainer
      - examples

jobs:
  build_sdks:
    name: Build SDKs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
        - nodejs
        - python
        - dotnet
        - go
        provider:
        - defang-aws
        - defang-gcp
        - defang-azure

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Setup and build SDK
      uses: ./.github/actions/build-sdk
      with:
        language: ${{ matrix.language }}
        provider: ${{ matrix.provider }}

    - name: Check worktree clean
      run: |
        git update-index -q --refresh
        if ! git diff-files --quiet; then
            >&2 echo "error: working tree is not clean, aborting!"
            git status
            git diff
            exit 1
        fi

    - name: Build Example
      run: make ${{ matrix.language }}_example
