name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{matrix.goversion}}
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.14.0
      with:
        repo: pulumi/pulumictl
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - run: make provider
    - run: make test
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64
        args: --timeout=5m --config=.golangci.yaml provider
    - name: Ensure schema and examples are up to date
      run: |
        make schema examples
        git diff -q provider/cmd/pulumi-resource-defang/schema-defang.json
        git diff -q ./examples
    
    strategy:
      fail-fast: true
      matrix:
        goversion:
        # - 1.18.x
        - 1.22.x

